### ISSUE TITLE
how does external snat works on windows CNI?

### ISSUE THREAD

**Issue by frederiksf** [aws/amazon-vpc-cni-k8s#1184]
How does external snat works on windows CNI? 

So far a i can see i cannot set this cni settings: "AWS_VPC_K8S_CNI_EXTERNALSNAT". I would like to do snat outside the cluster. Im using EKS 1.15 with a mix of linux and windows nodes.

**Comment by achevuru** [comment]
@frederiksf Windows CNI is a separate binary maintained @ https://github.com/aws/amazon-vpc-cni-plugins and it doesn’t support "AWS_VPC_K8S_CNI_EXTERNAL_SNAT”. There is no configurable option in Windows CNI to either enable or disable this feature. Windows CNI plugin should install a routing policy by default for this feature to work and if you don’t see the expected behavior in the current Windows CNI then it needs to be added in the CNI directly.

It does seem to skip SNAT *if* the destination is in the same subnet as the ENI. Maybe that should work as is for you if that is the case..

https://github.com/aws/amazon-vpc-cni-plugins/blob/master/plugins/vpc-shared-eni/network/bridge_windows.go#L178

**Comment by mogren** [comment]
@frederiksf Did the previous reply answer your question?
