### ISSUE TITLE
Add support for VPC Secondary CIDR ranges 

### ISSUE THREAD

**Issue by bchav** [aws/amazon-vpc-cni-k8s#131]
The CNI plugin needs to support allocation of IP addresses to pods from [secondary VPC cidr ranges](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#vpc-resize).

This will help customers who currently have limited IP space in their existing VPC. By adding another IP range and allocating IPs to pods from this IP range, customers can have more control over which IP space is consumed and can allocate CIDR blocks for pod use specifically. 

This design should support the primary interface for the node receiving an IP from the primary VPC CIDR range, and only pod IPs are allocated from the secondary range.

**Comment by sdavids13** [comment]
This seems to be related to #119. I believe an example use case + acceptance criteria could be:

- User has limited IP space allocated by a service provider due to various internal routing to different accounts
- Service provider will allow black listing a large CIDR block from transit routing, resulting in many VPCs using the same "internal only" secondary CIDR block for the CNI networking use. This secondary CIDR block will not be configured in route tables for VPC peering.
- Service provider needs to be able to access the host machine from a routable address (the primary IP address).
- Verify PODs with non-routable "internal only" secondary CIDR range IPs can continue to call out to services in peered VPCs.

**Comment by conversicachrisr** [comment]
This issue is blocking our move to EKS production use.

Note that this doesn't work even when the nodes and master endpoints are placed in the secondary VPC CIDR range, it's not just limited to placing pods in them. I'm not trying to do anything like #119.

**Comment by sdavids13** [comment]
@conversicachrisr what is the specific problem, are you running into issues while using calico described in #35?

**Comment by conversicachrisr** [comment]
You can't use EKS in a secondary CIDR block for any VPC. We are not running Calico, just EKS with the mandatory amazon-vpc-cni. This feature was added to VPC several months ago, and I guess EKS just never tested it.

Example:
VPC: 10.10.0.0/16
Additional VPC CIDR range: 10.11.0.0/16
EKS will not function in the secondary range. It will let you create the EKS cluster, and you can add nodes, but the networking will not function. This is the bare bones EKS setup, with zero customization or additions.

**Comment by bchav** [comment]
@conversicachrisr 

There are two parts to this problem- you're correct that nodes in a secondary CIDR range are not currently supported, but this is coming shortly. The second part is supporting a "split mode" with the CNI, where nodes can get IPs in the primary CIDR block and the CNI can allocate IPs to pods from the secondary range. One contingency that will remain is we will only (for now) support RFC1918 addresses, whether primary or secondary ranges on a VPC.

**Comment by sdavids13** [comment]
@bchav We have been running our EKS cluster in a secondary VPC cidr block. We are seeing some odd behavior where it mostly works but at times (~5%) things like helm and kubectl logs will just hang for a while and eventually timeout. When we retry in a couple of minutes it sometimes resolves itself, not sure if this is the same behavior others have been seeing but we don't have 100% failure. Though, for our case we are using HTTP proxies for most external communication which may be why it is partially working for us. Do you have an ETA for when the "secondary CIDR range" fix will be committed, we need to figure out if we are just going to bail on using EKS or not since we have some near-term deadlines.

Also, w/r/t RFC1918 support -- would that also include the 100.64.0.0/10 range as described in: https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html?shortFooter=true#vpc-resize

**Comment by pfremm-NM** [comment]
@bchav I see you have milestones v1.1, and v1.2.  Are tentative roadmap dates available?  The secondary VPC range is appealing.
