### ISSUE TITLE
Dangling ENIs without any association with Instances

### ISSUE THREAD

**Issue by Buffer0x7cd** [aws/amazon-vpc-cni-k8s#1447]
**What happened**:
During one of incidents , where pods are failing due to IP address exhaustion, We noticed that there a lots of ENIs that are allocated , But are not attached to any Instances.  Our first assumption was these might be the ENIs that are created to maintain warm pool on the nodes, But After checking them we discovered that there are no tags `node.k8s.amazonaws.com/instance_id `tags available on those ENIs, Which doesn’t seems like expected behaviour. 
https://github.com/aws/amazon-vpc-cni-k8s/blob/9db2ae62ecd0cb56f7fc20b80427fa6ff4e17a42/pkg/awsutils/awsutils.go#L606 
As far i can see, Allocation and attachment of ENIs are so there shouldn’t be the case where ENIs are allocated but are not attached and have missing tags, Except here (https://github.com/aws/amazon-vpc-cni-k8s/blob/9db2ae62ecd0cb56f7fc20b80427fa6ff4e17a42/pkg/awsutils/awsutils.go#L616
 ENI attach and delete both failed). To verify this i checked the prometheus metrics for `AttachNetworkInterface` api for any errors , but there are no significant increases here that explains this being the cause of increase in Allocated ENIs.

**Comment by jayanthvn** [comment]
Hi @Buffer0x7cd 

Do you have short lived instances/cluster? Also do you have any node termination policy? There is one known issue (https://github.com/aws/amazon-vpc-cni-k8s/issues/1223), After ENI is detached, it will take few seconds for the ENI to delete, if in the mean time node is terminated then the ENI will be dangling in the account.

**Comment by Buffer0x7cd** [comment]
HI @jayanthvn 

It doesn’t seems like this is the issue. https://github.com/aws/amazon-vpc-cni-k8s/blob/9db2ae62ecd0cb56f7fc20b80427fa6ff4e17a42/pkg/awsutils/awsutils.go#L836
From my understanding , In the case here. ENI will be First detached and deleted. Assuming the ENI was first Attached It should have the `node.k8s.amazonaws.com/instance_id` tag, Even after being detached  ( As there is no steps to delete tags in the `freeENI` method).

In our observed case we can see that the dangling ENIs have no `node.k8s.amazonaws.com/instance_id` tag available , Which should be present if these Dangling ENIs were due to https://github.com/aws/amazon-vpc-cni-k8s/issues/1223

**Comment by jayanthvn** [comment]
Yeah makes sense, I quickly ran a test and detached an ENI and I still see the instance_id tag even though the ENI is detached. Can you please open a support case?

**Comment by jayanthvn** [comment]
Hi @Buffer0x7cd 

For the ENI, do you see the "node.k8s.amazonaws.com/createdAt" tag present?

**Comment by Buffer0x7cd** [comment]
@jayanthvn yes i can see the node.k8s.amazonaws.com/createdAt at tag present

**Comment by jayanthvn** [comment]
Thanks for checking @Buffer0x7cd. So looks like createENI is fine but if attachENI failed we would have deleted the ENI - https://github.com/aws/amazon-vpc-cni-k8s/blob/9db2ae62ecd0cb56f7fc20b80427fa6ff4e17a42/pkg/awsutils/awsutils.go#L612-L614. If you can open a support case, then we can check EC2 logs to confirm why attachENI failed.

**Comment by aclevername** [comment]
We've noticed this while working in https://github.com/weaveworks/eksctl/ too. We recently managed to reproduce this issue: https://github.com/weaveworks/eksctl/issues/4214#issuecomment-923871267

**Comment by hiattp** [comment]
We're seeing a similar/related issue but have cases where none of the active pods have ENIs that are attached to instances (the node has 2 ENIs with 10 and 1 private IP addresses respectively, and there are 13 pods on the node none of which use those ENIs). Not sure if this is actually the same issue but we've raised a support ticket (9328577341). The original reason we raised the ticket was due to pods getting stuck in Pending with events like:

> Warning  FailedScheduling   21s (x12 over 13m)    default-scheduler   0/10 nodes are available: 4 node(s) didn't match node selector, 6 Insufficient vpc.amazonaws.com/pod-eni.

And further investigation led us to this ticket, but it's unclear whether the issues are related.

**Comment by GaruGaru** [comment]
Same issue running `v1.7.5-eksbuild.1` on `v1.21.5-eks-9017834`.
We have many unused ENI interfaces with just the `node.k8s.amazonaws.com/createdAt` tag set

**Comment by bryantbiggs** [comment]
Not stale

**Comment by jayanthvn** [comment]
@aclevername - in the issue you mentioned we do see the `node.k8s.amazonaws.com/instance_id`. Typically this happens when node is terminated between delete and detach ENI calls.

@bryantbiggs or @GaruGaru - Can one of you please share IPAMD logs? You can email the log bundle to - `k8s-awscni-triage@amazon.com`

**Comment by bryantbiggs** [comment]
Not stale

**Comment by timblaktu** [comment]
Tagging teammate @vidhyadharm about this "dangling ENI" issue, suggested by @bryantbiggs as root cause for [our vpc deletion issue in eks blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/968#issuecomment-1249746379) and [the corresponding vpc deletion issue in aws vpc module](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/283).

**Comment by yukccy** [comment]
Is there any fix for this issue? Coming from https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/283 that cannot delete VPC due to DependencyViolation

**Comment by NathanDotTo** [comment]
This still appears to be an issue. It seems that the only workaround is to manually delete the VPC.

**Comment by jeremyzti** [comment]
I don't know if this will help (I'm new to Terraform) ... my destroys are also failing. 

Then I delete (in this order) 
- EBS volumes
- load balancers
- subnets
- security groups (except defaults)
- VPC 
and now terraform destroy finds nothing left to delete

**Comment by yash97** [comment]
Hi folks, does anyone have cloud trail events for the dangling ENIs that is being observed here? Would appreciate full events or summary of your events from your side. Also feel free to send the events if possible on this email https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#collecting-node-level-tech-support-bundle-for-offline-troubleshooting.

**Comment by yash97** [comment]
@jeremyzti can you please add more context on how terraform destroys relate to this issue? Did you see dangling ENI's that were created by cni not being deleted? Would appreciate more details, related to eni lifecycle, cluster lifecycle and cloud trail event if possible. 

Generic question has anyone able to reproduce this issue?

**Comment by bryantbiggs** [comment]
as the maintainer of https://github.com/terraform-aws-modules/terraform-aws-eks, I thought I'd add a few scenarios we've seen the most issues encountered over the years:

1. Not setting `preserve = true` on the VPC CNI addon so that the daemon continues to run on nodes during the Terraform destroy process. Otherwise, the addon is removed early and unable to clean up its resources
2. The IAM role used by the ec2 instance profile and/or IRSA or EKS Pod Identity is removed too early (they get removed early in the process since they have little to zero dependencies in the Terraform state graph). Once removed, the CNI lacks permissions to continue managing the ENIs it created/attached

For those that are experiencing the issue, seeing the configurations and steps performed to reproduce the issue would be helpful

**Comment by jeremyzti** [comment]
Please feel free to tell me to RTFM because I'm not sure what you're asking for. My basic workflow is terraform apply; helm install; terraform destroy. I got my terraform files from https://github.com/hashicorp-education/learn-terraform-provision-eks-cluster although I did have to make some tweaks to get a cluster big enough for my application.  The destroy always ends with errors like these. I can collect logs, I just need to know how to generate and/or where to look. 

`Error: deleting EC2 Internet Gateway (igw-06bda4cc34861fe43): detaching EC2 Internet Gateway (igw-06bda4cc34861fe43) from VPC (vpc-01d4698c326741be9): DependencyViolation: Network vpc-01d4698c326741be9 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway. 
status code: 400, request id: e9c06fd2-90e3-440c-97c8-7e4fb82413f3

Error: deleting EC2 Subnet (subnet-0abf5782fd8b80667): DependencyViolation: The subnet 'subnet-0abf5782fd8b80667' has dependencies and cannot be deleted.
status code: 400, request id: 8c69abf6-6339-43e8-9ae5-15c193d0a552`

**Comment by bryantbiggs** [comment]
Infrastructure defined as code is one giant dependency graph. The more you do in the framework, the more the framework can understand dependencies correctly. However, its not possible to do everything in the IaC framework, plus there are edge cases where you need to make accommodations. 

I'll share one common scenario, but know there are many scenarios where you can encountered these dependency conflicts. And if you want to skip to the tl;dr - split your infrastructure configurations into separate, discrete layers. Your networking is defined and created in one layer, your cluster infrastructure (control plane, node groups, etc.) a second layer, and the applications that are deployed onto the cluster in a third layer. You create via 3 applies in series - networking, cluster, applications. And you destroy in the reverse order - applications, cluster, networking. That will solve your issues in 99.999% of scenarios

Take a simple cluster configuration that deploys an EKS managed node group, the core addons of VPC CNI, kube-proxy, and CoreDNS are deployed via the EKS addons API, and the AWS load balancer controller (LBC) is deployed via its Helm chart. In your configuration you have also created a simple VPC spanning 3 AZs with both public and private subnets as well as IGW and NAT gateway. For simplicity, all of this is codified in Terraform in one statefile/directory.

On apply, the resources should all succeed in provisioning and deploying successfully but there are some nuances that get masked (i.e. - failures that are silently handled). The AWS LBC deployed via the `helm_release` resource tries to provision early, as soon as the control plane endpoint is available, but will continue to fail and retry until it succeeds. Depending on your scenario this may or may not succeed, and you could opt to not let the resource [wait](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/69c976cec70917afa103b267d71d7dcf45d52ec3/patterns/karpenter/karpenter.tf#L42) for a success signal and simply just "fire and forget", relying on Kubernetes controllers to eventually reconcile and succeed. However, through retries and reconciliation, in most cases the resources eventually all provision and deploy and the Terraform apply completes successfully.

On destroy, the story is a bit worse. When creating resources, everything is working towards the same goal - reach the deployed/provisioned state without error. When destroying/deprovisioning, the story is different - some resources are working towards the goal of stopping/deleting while others are continuing to operate in a "normal" state. This causes conflicts. Coupled with the dependency graph which will dictate the ordering of resource deletion, you can reach undesirable states where resources that are continuing to try to operate in their "normal" state are suddenly without the facilities they required. 

In the example above, there are no dependencies on the AWS LBC helm chart, but it will take some between the Helm commands to delete and pods finalizing and stopping. There are also no dependencies on the IAM role used/required by the AWS LBC (IRSA or EKS Pod Identity), and IAM roles are deleted very quickly - taking less time than it takes for the AWS LBC to clean up its resources. This is a problem - with the IAM role gone, the AWS LBC is unable to clean up any of the AWS resources it created. Those resources will remain in place and then cause the VPC resource to fail to delete. Subnets cannot be deleted if they still contain ENIs. 

I believe the VPC CNI used to operate in a similar manner and dangling ENIs (created by the VPC CNI) controller were more prevalent. However, the EKS service has made some changes to better counteract this so I would go back and take a deeper look at the ENIs, or networking resources in general given that your error message shows an IGW, and try to determine who or what created those resources that are preventing deletion. I suspect you'll find its not the VPC CNI and potentially a different resource like the AWS LBC (NGINX ingress controller and the like all do the same) and you'll need to modify your process for destroying resources created by Terraform accordingly.

**Comment by jeremyzti** [comment]
Thanks Bryant. I have adjusted my workflow to be 

1. terraform apply
2. helm install (times 2) plus some kubectl applies 
3. run my tests
4. helm uninstall (times 2)
5. kubectl delete pvc --all 
6. terraform destroy 

and now it's reliably cleaning up.
