### ISSUE TITLE
When withOIDC: true, nodes always NotReady in fully-private cluster 

### ISSUE THREAD

**Issue by yufan022** [aws/amazon-vpc-cni-k8s#1473]
```
iam:
  withOIDC: true
privateCluster:
  enabled: true
```
Node can't join to fully-private cluster when I set `withOIDC:true` and `privateCluster.enabled: true`.

`kubectl get nodes` state is `NotReady` all the time. 
```
NAME                                             STATUS     ROLES    AGE     VERSION
ip-10-0-18-198.ap-northeast-1.compute.internal   NotReady   <none>   3m31s   v1.19.6-eks-49a6c0
```

How can I set `withOIDC: true` on `fully-private cluster`?
Is this related #647 ? 

kubelet log
```
May 25 06:51:15 ip-10-0-29-116 kubelet: E0525 06:51:15.788460    4532 kubelet.go:2108] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
May 25 06:51:16 ip-10-0-29-116 kubelet: W0525 06:51:16.885288    4532 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
May 25 06:51:17 ip-10-0-29-116 su: (to root) ec2-user on pts/0
May 25 06:51:20 ip-10-0-29-116 kubelet: E0525 06:51:20.796170    4532 kubelet.go:2108] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
May 25 06:51:21 ip-10-0-29-116 kubelet: W0525 06:51:21.885384    4532 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
May 25 06:51:25 ip-10-0-29-116 kubelet: E0525 06:51:25.803685    4532 kubelet.go:2108] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
May 25 06:51:26 ip-10-0-29-116 kubelet: W0525 06:51:26.885495    4532 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
```

cni log
```
[root@ip-10-0-1-46 ~]# kubectl logs aws-node-tdrnj -n kube-system
{"level":"info","ts":"2021-05-25T06:59:57.099Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-05-25T06:59:57.110Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-05-25T06:59:57.112Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
```

kubectl describe nodes
```
  MemoryPressure   False   Tue, 25 May 2021 07:01:54 +0000   Tue, 25 May 2021 05:21:08 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Tue, 25 May 2021 07:01:54 +0000   Tue, 25 May 2021 05:21:08 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Tue, 25 May 2021 07:01:54 +0000   Tue, 25 May 2021 05:21:08 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Tue, 25 May 2021 07:01:54 +0000   Tue, 25 May 2021 05:21:08 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

kubectl describe pods -n kube-system aws-node-98b7h
```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  7m56s                   default-scheduler  Successfully assigned kube-system/aws-node-98b7h to ip-10-0-23-140.ap-northeast-1.compute.internal
  Normal   Pulling    7m42s                   kubelet            Pulling image "602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon-k8s-cni-init:v1.7.5-eksbuild.1"
  Normal   Pulled     7m38s                   kubelet            Successfully pulled image "602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon-k8s-cni-init:v1.7.5-eksbuild.1" in 3.824615724s
  Normal   Created    7m36s                   kubelet            Created container aws-vpc-cni-init
  Normal   Started    7m36s                   kubelet            Started container aws-vpc-cni-init
  Normal   Started    7m33s                   kubelet            Started container aws-node
  Normal   Pulled     7m33s                   kubelet            Successfully pulled image "602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 1.601084943s
  Warning  Unhealthy  7m30s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:01:46.801Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  7m20s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:01:56.805Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  7m10s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:02:06.809Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  7m                      kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:02:16.797Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  6m50s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:02:26.809Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  6m40s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:02:36.813Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  6m30s                   kubelet            Liveness probe failed: {"level":"info","ts":"2021-05-25T08:02:46.765Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  6m30s                   kubelet            Readiness probe failed: {"level":"info","ts":"2021-05-25T08:02:46.789Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Warning  Unhealthy  6m20s                   kubelet            Liveness probe failed: {"level":"info","ts":"2021-05-25T08:02:56.757Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
  Normal   Killing    6m10s                   kubelet            Container aws-node failed liveness probe, will be restarted
  Normal   Pulling    6m (x2 over 7m35s)      kubelet            Pulling image "602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1"
  Normal   Created    5m59s (x2 over 7m33s)   kubelet            Created container aws-node
  Normal   Pulled     5m59s                   kubelet            Successfully pulled image "602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 176.591971ms
  Warning  Unhealthy  2m40s (x30 over 6m20s)  kubelet            (combined from similar events): Readiness probe failed: {"level":"info","ts":"2021-05-25T08:06:36.801Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
```

**Comment by tgeoghegan** [comment]
I encountered what appears to be the same problem. I had configured the `vpc-cni` addon to use an IAM role via OIDC with the `AmazonEKS_CNI_Policy` canned policy attached. I was able to get past this problem by instead attaching that policy to the worker node IAM role and then letting the `vpc-cni` addon inherit the node role.

**Comment by misiektoja** [comment]
> I encountered what appears to be the same problem. I had configured the `vpc-cni` addon to use an IAM role via OIDC with the `AmazonEKS_CNI_Policy` canned policy attached. I was able to get past this problem by instead attaching that policy to the worker node IAM role and then letting the `vpc-cni` addon inherit the node role.

Thanks for the hint, I finally got the private cluster working. However to extend your reply little bit, it is important to:
- have 'withOIDC: false' 
- attach  arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy for nodes, for example in managedNodeGroups section: 
    iam: &iam
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

I also changed the global STS as 'Valid in all AWS Regions' in IAM account settings and set usage of regional STS endpoints in AWS CLI. Not sure if it had any impact, but just listing it here for completeness (maybe somebody will be able to confirm if it was relevant). Anyway, it works.

**Comment by tgeoghegan** [comment]
It does work, but for the benefit of any AWS people reading this, I think it's worth noting that it's an imperfect workaround. As recommended in the AWS EKS guide, I'd prefer to restrict the permissions `AmazonEKS_CNI_Policy` to an IAM role granted to the VPC CNI plugin rather than extending those permissions to the entire worker node.

**Comment by jayanthvn** [comment]
Possibly similar to this - https://github.com/weaveworks/eksctl/issues/1672. This https://github.com/aws/amazon-vpc-cni-k8s/pull/1332 will be taken up in 1.8 which fixes this https://github.com/aws/amazon-vpc-cni-k8s/issues/647

**Comment by davisford** [comment]
> I encountered what appears to be the same problem. I had configured the vpc-cni addon to use an IAM role via OIDC with the AmazonEKS_CNI_Policy canned policy attached. I was able to get past this problem by instead attaching that policy to the worker node IAM role and then letting the vpc-cni addon inherit the node role.

@tgeoghegan can you clarify a bit what you mean by this?  I'm currently using [eksctl](https://eksctl.io/) to spawn my cluster.  I have OIDC enabled and both public/private networks set to true.  I am also using managed nodegroups and I am attaching the canned AmazonEKS_CNI_Policy directly to the node via the nodegroup configuration a la (this YAML config is documented for `eksctl` [here](https://eksctl.io/usage/schema/):

```yaml
// etc....
vpc:
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true
serviceAccounts:
// etc....

managedNodeGroups:
  - name: some-nodegroup
    instanceType: t.something
    availabilityZones: ["us-somewhere"]
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/{cluster-name}: "owned"
    amiFamily: AmazonLinux2
    ssh:
      enableSsm: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

So the CNI policy role is attached to the node (per my understanding) via that nodegroup.  I would also prefer to restrict the roles to use [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) so only certain pods (not nodes) get whatever permissions they need, but not at the detriment of having my cluster just fail (which it is right now...incidentally...multiple nodes sitting in the `NotReady` state b/c of some issue related to this?)

> I also changed the global STS as 'Valid in all AWS Regions' in IAM account settings and set usage of regional STS endpoints in AWS CLI (export AWS_STS_REGIONAL_ENDPOINTS=regional). Not sure if it had any impact, but it was listed on some other page, so just listing it here for completeness (maybe somebody will be able to confirm if it was relevant). Anyway, it works.

@misiektoja can you or anyone else here confirm that this is the missing piece of the puzzle?  I have not changed any of this in IAM settings, and am now still wondering how to fix this.

#FWIW I do have an open ticket with AWS on this and have basically been debugging it most of the day with them -- still waiting on more info now.  When I find root cause and resolution, I'll be happy to drop it here hoping it helps...

**Comment by tgeoghegan** [comment]
I am not using `eksctl` but if I'm reading your YAML correctly, then what you've got set up is what I have described as a workaround: you attach `AmazonEKS_CNI_Policy` to the IAM role for the nodes, then don't specify an IAM role for the `vpc-cni` EKS addon, which causes it to inherit the IAM role used by the node. The API requests subsequently made by the `vpc-cni` addon then succeed. The downside to this approach is that anything that runs as the worker node role is unnecessarily granted access to various VPC APIs (whatever permissions are in `AmazonEKS_CNI_Policy`), and it also means the `vpc-cni` addon is granted a variety of permissions it doesn't need (`AmazonEKSWorkerNodePolicy`, `AmazonEC2ContainerRegistryReadOnly`, `AmazonSSMManagedInstanceCore`).

It is possible to configure the `vpc-cni` EKS add-on with an IAM role distinct from the worker node role [using IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html). However this doesn't work on clusters with fully private networks, and it seems to be because the `vpc-cni` pod can't reach the `sts.amazonaws.com` endpoint in order to exchange a Kubernetes service account token for AWS IAM credentials.

I don't think it matters whether or not your EKS Kubernetes cluster endpoint is publicly or privately accessible, because this isn't a question of the pod reaching the Kubernetes API but rather the pod reaching `sts.amazonaws.com`. However, I can't be sure if the failure you are observing is the same as what I ran into.
