### ISSUE TITLE
Discrepancy in Calico Manifest files vs Helm chart 

### ISSUE THREAD

**Issue by aquam8** [aws/amazon-vpc-cni-k8s#1517]
Discrepancy in Calico Manifest files vs Helm chart (within the repository)

I could not help noticing how the the Calico install/deloyment is different in the manifest files (config/v1.x/) and the Helm charts (charts/aws-calico/). Application versions are different (3.15.1 vs 3.17.1). Use of Tigera operator vs not etc..

Is this on purpose? Are the Helm chart for Calico to be deprecated?

Thank you!

**Comment by jayanthvn** [comment]
Hi @aquam8 

Yes there is a discrepancy now since in aws-vpc-cni/master there were changes done like Tigera operator which you mentioned which is yet to be fixed in eks-charts. We are having a discussion with calico team and going forward we are thinking of making the changes in aws-vpc-cni/charts and export that automatically to eks-charts. Which we are already doing it for aws-vpc-cni manifests.

**Comment by aquam8** [comment]
That would be great, thank you. I’m glad that it’s on the roadmap as I
could not find an open issue ToDo for it.

Thanks!

**Comment by M00nF1sh** [comment]
@aquam8 
Calico team prefer to install calico via this tigera operator(which bundles a specific calico version), while our aws-calico helm chart is install calico directly.
we are thinking whether to upgrade aws-calico to use tigera(which breaks backwards-compatibility) or deprecate it and replace it with another chart like aws-tigera-operator. Any preferences?

**Comment by aquam8** [comment]
Yes I noticed how it uses a new namespace and inject the docker image
repository and version to use for Calico.
I understand that publishing it through manifest is a lot easier than than
having to manage this through the helm chart.

My 2 concerns:
- if we use the Tigera Operator we should be able to pass in our own docker
image for calico (repository and version) so we can manage the versioning
ourselves if in the future there’s a bug on a particular version of calico
(or vulnerability to patch)

- breaking backward compatibility is a problem, and I would say that maybe
a separate helm chart that could be installed in parallel would be a good
solution. But if 2 installs would cause failure then either we explicitly
ask to uninstall one before the other one is installed. But then you may as
well introduce breaking backward and require people to uninstall existing
chart before upgrading…

I should mention that there is an open issue on Calico that is causing
problem for EKS clusters using aws-vpc-cni when calico is installed with
tigera operator (3.16+)
https://github.com/projectcalico/calico/issues/4518
Today the only documented install that works is through the helm chart as
it installs 3.15.1.

So be mindful of that as you prepare the charts for calico tigera.

Cheers

**Comment by johnthedev97** [comment]
In my opinion backward compatibility is already broken between 1.7.8 and 1.7.9.

We have an automation which manage EKS clusters with automation and we have been installing it using the previous official documentation

![image](https://user-images.githubusercontent.com/23088021/122948873-87570f80-d37b-11eb-8d37-204edf9646e1.png)

From 1.7.9, onward that doesn't work. The apply would create an operator, the operator silently fails because it detects an existing installation. The new official document doesn't have any mention of upgrading calico from previous installation done via the official documentation. The only option I see is to uninstall previous (1.7.8 or early) installations and then install the new one. The impact of this on a production system with existing policies is not clear to me.

Also, the switch to operator model also seems to switch the image registry to docker.io from quay.io, and for us docker.io is not practically usable. 

I am still trying the best way to switch and upgrade, any suggestions are welcome. It would be great if the official documenation includes steps for switching to the new model. Thanks in advance.

**Comment by M00nF1sh** [comment]
@johnthedev97 
Thanks for calling this out. I'll work with our docs team next week to call this out in our documentation.

**Comment by stevehipwell** [comment]
The official Calico Helm operator chart is due to be published [this month](https://github.com/projectcalico/calico/issues/4514#issuecomment-859649993) so shouldn't EKS use this?

**Comment by jayanthvn** [comment]
#1541 is merged and we picked official calico charts to this repo.
