### ISSUE TITLE
Question: hostNetwork and privileged

### ISSUE THREAD

**Issue by groodt** [aws/amazon-vpc-cni-k8s#1521]
It probably makes sense given the nature of this add-on, however, I thought that I should ask anyway.

Does the aws-node DaemonSet require `hostNetwork` access?
Does the aws-vpc-cni-init container require the `privileged` SecurityContext?

Could you possibly comment on what it's used for?

**Comment by jayanthvn** [comment]
Hi @groodt 

aws-node is a `hostNetwork` pod mainly because we need an IP for a regular pod and with the current design without `aws-node` pod cni and ipamd won't be running. Also we would want localhost:50051 to be available for cni plugin to talk to IPamD.

We wanted long running pod `aws-node` not to be privileged but still we need certain configs like setting rp_filter and tcp_v4_early_demux which cannot be set with NET_ADMIN permissions hence we have short lived `aws-vpc-cni` init container as privileged.

**Comment by groodt** [comment]
@jayanthvn Thanks for the detailed response. That makes sense.

Is there a similar justification for the `cni-metrics-helper`?

**Comment by jayanthvn** [comment]
@groodt - CNI metrics helper is not host networking and doesn't have privileged access.

**Comment by groodt** [comment]
> @groodt - CNI metrics helper is not host networking and doesn't have privileged access.

Thanks @jayanthvn Maybe I've patched it through in my deployment because I didn't set it up with IRSA. Is there now an official guide for setting up amazon-vpc-cni-k8s and cni-metrics-helper with IRSA? Is it officially supported from a particular version?

**Comment by jayanthvn** [comment]
Hi @groodt 

This is the guide to setup IRSA for amazon-vpc-cni-k8s - https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html. For cni-metrics-helper, we don't support yet - https://github.com/aws/amazon-vpc-cni-k8s/issues/1287. If you can please share me the K8s and CNI version I can confirm if IRSA is supported.

**Comment by groodt** [comment]
> For cni-metrics-helper, we don't support yet - #1287. If you can please share me the K8s and CNI version I can confirm if IRSA is supported.

K8s 1.20
CNI (we are currently on v1.7.5, but can upgrade to v1.8.0)

**Comment by jayanthvn** [comment]
Yes IRSA is supported with this for cni.

**Comment by jayanthvn** [comment]
Please do reach out if you need any more information. Thank you!
