### ISSUE TITLE
How to stop scheduling pods when aws-cni is not ready

### ISSUE THREAD

**Issue by njuettner** [aws/amazon-vpc-cni-k8s#1523]
**What happened**:

In case of aws-cni is not ready yet, we often face issues by Kubernetes already scheduling pods but can't get an IP address when aws-cni is not up correctly. I wonder if there's a way that aws-cni could notify node once it's ready by setting taint on the nodes or something. Are there any plans for such use-case or is there even already something which we could pick up?

It would definitely help us, otherwise we might need to implement this by ourself.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.x
- CNI Version 1.8.0
- OS (e.g: `cat /etc/os-release`): flatcar 
- Kernel (e.g. `uname -a`): 5.x

**Comment by jayanthvn** [comment]
Hi @njuettner 

Node will not be marked as ready until `aws-node` is up. We copy the config after IPAMD is up - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/entrypoint.sh#L145. So are you referring to a scenario where ENI has no IP but the `aws-node` is UP so until the next reconciler starts IPs won't be attached so pods won't get IPs?

Thanks!

**Comment by njuettner** [comment]
Correct, in case an IP can't be allocated because of IP exhaustion.

**Comment by jayanthvn** [comment]
@njuettner currently there is no support for this but adding something like a taint is a nice suggestion. Also we had plans to look into this - https://github.com/aws/amazon-vpc-cni-k8s/issues/1160 which will help your use case too. We haven't yet scoped down the tasks on this but I can review this in couple weeks and get back to you?

**Comment by njuettner** [comment]
@jayanthvn this sounds super cool, it would be great if you can make it possible 👍🏻

**Comment by jayanthvn** [comment]
@njuettner - Thanks, will look into it and will try to get to this in couple weeks.

**Comment by njuettner** [comment]
@jayanthvn 👋🏻  did you already had some time looking into it?

**Comment by jayanthvn** [comment]
@njuettner Sorry was on vacation last week, will discuss this internally within the team and provide an update.

**Comment by njuettner** [comment]
@jayanthvn Thank you 👍🏻

**Comment by njuettner** [comment]
@jayanthvn any updates on this issue?

**Comment by njuettner** [comment]
@jayanthvn I'm sorry bothering you but is there any chance to get feedback from you or the team?

**Comment by jayanthvn** [comment]
@njuettner - Sorry for the delay.

I was discussing with @achevuru. One improvement which can be done here is - Typically when IP is not available, create will fail and kubelet will send a delete. Now this delete will return an error with existing code since pod is not found https://github.com/aws/amazon-vpc-cni-k8s/blob/146b9b910a89accf2a7e6bc1199dff10a8806e6b/pkg/ipamd/datastore/data_store.go#L1179 in IPAMD store and kubelet will keep retrying deletes. Since the IP is not allocated in the first place, IPAMD delete should instead reply with a success. So at least now the pod "might" be scheduled on a new node which might have the IPs available.

@achevuru want to add anything here?

**Comment by njuettner** [comment]
It would be great if there would be a way, to circumvent this issue. Is there any PR available or branch which I could try to test if it would improve the situation?

**Comment by njuettner** [comment]
@achevuru any ideas from your side?
