### ISSUE TITLE
SG update does not update Pod SG rules

### ISSUE THREAD

**Issue by skydacremam** [aws/amazon-vpc-cni-k8s#1532]
**What happened**:
Using EKS security groups for Pod I notice that if I change inbound rules on SG these are not updated on the pod side and the pod remains unreachable. I need to provision a new pod.

**Attach logs**
Not able to provide logs

**What you expected to happen**:
I expect that rules are synced with pod SecurityGroupPolicy
**How to reproduce it (as minimally and precisely as possible)**:
Create a SG, associate to a pod, verify connectivity from one allowed IP, update SG to allow a new IP, verify that pod is still unreachable from the IP you allowed in the SG
**Anything else we need to know?**:

**Environment**: EKS 1.20 eks.1
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- CNI Version
amazon-k8s-cni-init:v1.7.10-eksbuild.1
amazon-k8s-cni:v1.7.10-eksbuild.1
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by haouc** [comment]
Hey @skydacremam, thanks for reporting this issue. I will try to reproduce it in my cluster and update with you soon.

**Comment by abhipth** [comment]
Hi @skydacremam 

I was unable to reproduce the issue. I have attached my test results below for reference. Since the traffic to/from the Pod flows through the ENI always, it will be subjected to the current rules of the Security Group. Once the new SG rules are applied on the ENI, any incoming traffic to the existing Pod should be subjected to the new SG rules.

You can also confirm the same by doing exec into the existing Pod once you have added the new Inbound Rule and capture the TCP dump on the new port while you send traffic. 

Also to further investigate, could you provide the following details.
- The traffic type including the new protocol that you are allowing on the SG.
- Description of the failure mode due to which you have to recreate a new Pod.


## Test Results

### Setup 
I have got two nodes, and 3 test Pods. 

```
SGP Pod - 192.168.40.134 [node: ip-192-168-41-190.us-west-2.compute.internal]
Traffic Pod 1 - 192.168.89.250 [node: ip-192-168-93-99.us-west-2.compute.internal]
Traffic Pod 2 - 192.168.41.227 [node: ip-192-168-41-190.us-west-2.compute.internal]
```

SGP Pod and Traffic Pod 2 are on Same Node. 
I am using `nc` to listen on the SGP Pod and connect from the Traffic Pod.

### When SGP has Port 8080 Open for Inbound Connection

**Connecting from Traffic Pods to Port 8080**

```
  Trafif Pod 1: nc 192.168.40.134 8080 -v
  SGP Pod: connect to [::ffff:192.168.40.134]:8080 from [::ffff:192.168.89.250]:44521 ([::ffff:192.168.89.250]:44521)

  Traffic Pod 2: nc 192.168.40.134 8080 -v
  SGP Pod: connect to [::ffff:192.168.40.134]:8080 from [::ffff:192.168.41.227]:34331 ([::ffff:192.168.41.227]:34331)
```

This succeeds as expected as SG has port 8080 open.

**Connecting from Traffic Pods to Port 8081**

```
  Traffic Pod 1: nc 192.168.40.134 8081 -v
  SGP Pod: listening on [::]:8081 ...

  Traffic Pod 2: nc 192.168.40.134 8081 -v
  SGP Pod: listening on [::]:8081 ...
```

This fails as expected as the SG doesn't have port 8081 open.


### After adding Inbound Rule 8081 on the SG

```
  Traffic Pod 1: nc 192.168.40.134 8081 -v
  SGP Pod: connect to [::ffff:192.168.40.134]:8081 from [::ffff:192.168.89.250]:39497 ([::ffff:192.168.89.250]:39497)

  Traffic Pod 2: nc 192.168.40.134 8081 -v
  SGP Pod: connect to [::ffff:192.168.40.134]:8081 from [::ffff:192.168.41.227]:39017 ([::ffff:192.168.41.227]:39017)
```

Connection on port 8081 works as expected without needing to restart the Pod.

**Comment by jayanthvn** [comment]
@skydacremam - Please let us know if you are still having this issue?

**Comment by jayanthvn** [comment]
@skydacremam - Can you please confirm if the issue is still happening? If so, can you please run this script on the instance - `sudo bash /opt/cni/bin/aws-cni-support.sh` and share us the logs?
