### ISSUE TITLE
Disk may fill up quickly with Multus debug logging.

### ISSUE THREAD

**Issue by dougbtv** [aws/amazon-vpc-cni-k8s#1566]
Just a quick report that I noticed this in the Multus configuration yaml: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/multus/v3.7.2-eksbuild.1/aws-k8s-multus.yaml#L196-L197

Which I found from reading this article: https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/

Just a note that debug level logging is rather chatty, and could quickly fill up disks at scale. I'd recommend using the "verbose" log level, which will report some events, as well as errors, but won't be quite as chatty as the "debug" log level.

The "error" log level might also be appropriate if you don't need to see success events.

More info available in the Multus logging docs @ https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/configuration.md#logging-level

**Comment by s1061123** [comment]
Hi aws folks, I and @dougbtv, are main committer of Multus-CNI in Kubernetes Networking Plumbing working group (NPWG).

As Doug mentioned, `--multus-log-level=debug` is mainly for development or troubleshooting because it generates a very long debug output. Hence we strongly recommend to change `debug` to `error` or `verbose`.

**Comment by s1061123** [comment]
Hi aws folks (@cgchinmay), I and @dougbtv, are main committer of Multus-CNI in Kubernetes Networking Plumbing working group (NPWG).

As Doug mentioned, --multus-log-level=debug is mainly for development or troubleshooting because it generates a very long debug output. Hence we strongly recommend to change debug to error or verbose.

**Comment by cgchinmay** [comment]
I will updated it to verbose. Thanks for pointing it out

**Comment by jayanthvn** [comment]
#1567 merged.
