### ISSUE TITLE
tigera-operator failing in ARM64 

### ISSUE THREAD

**Issue by rijub2019** [aws/amazon-vpc-cni-k8s#1708]
~] kubectl logs tigera-operator-6fbb48778f-kdvmd -n tigera-operator
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by jayanthvn** [comment]
@tmjd - #1710 is pending review to support ARM.

**Comment by haouc** [comment]
@rijub2019 
Since we are deprecating Calico charts in this repo and this should be fixed in Tigera/Calico release v3.22, we recommend you to refer to our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html). You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
