### ISSUE TITLE
request to update calico-operator manifest to install calico >= 3.21.0

### ISSUE THREAD

**Issue by kashook** [aws/amazon-vpc-cni-k8s#1782]
Pull request #1629 added the `ANNOTATE_POD_IP` option to the aws-vpc-cni plugin to annotate pods with their IP address to address pod startup network latency with Calico. Calico has recently released version 3.21.0 (see [release notes](https://docs.projectcalico.org/archive/v3.21/release-notes/)), which includes [this update](https://github.com/projectcalico/libcalico-go/pull/1523) to actually read the annotation added by the aws-vpc-cni when `ANNOTATE_POD_IP` is set. This is a request to update the [calico-operator manifest](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/calico-operator.yaml) referred to by this [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) to install a tigera operator version that will install version 3.21.0 or higher of Calico so that we can eliminate the network latency issue on pod startup in our EKS cluster.

**Comment by haouc** [comment]
@kashook Since we are deprecating Calico charts in this repo and this feature is already supported in new version of Calico, please refer to our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) to upgrade Calico.
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com) if you have.
