### ISSUE TITLE
calico-typha preventing cluster upgrades

### ISSUE THREAD

**Issue by L1ghtman2k** [aws/amazon-vpc-cni-k8s#1819]
**What happened**:
This attempts to cover a similar topic as https://github.com/aws/amazon-vpc-cni-k8s/issues/1598.

Calico-tigera schedules typha workloads on tainted nodes, hence preventing cluster upgrades:
https://github.com/tigera/operator/issues/1441
https://github.com/projectcalico/calico/issues/4695

This issue could be resolved by using `controlPlaneTolerations` that were introduced in `v1.13.10` of tigera operator by overwriting the broad default tolerations typha receives. However, `controlPlaneTolerations` only started applying to typha pods with `v1.22.0` of tigera (https://github.com/tigera/operator/commit/ef4c15f4cdfdcf17e358416aaf0f5269c8521bbd / https://github.com/projectcalico/calico/issues/4695)

**What you expected to happen**:
I expect EKS managed nodes to be upgraded without any issues

**Anything else we need to know?**:
upgrading to tigera operator  `>=v1.22.0` will allow the use of `controlPlaneTolerations` to prevent tigera from scheduling typha on tainted nodes

**Comment by haouc** [comment]
@L1ghtman2k Since we are deprecating Calico charts in this repo and this feature is already supported in new Tigera operator, please refer to our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com) if you have.
