### ISSUE TITLE
Fix error handling in node label update path

### ISSUE THREAD

**Issue by vikasmb** [aws/amazon-vpc-cni-k8s#1887]
**What happened**:

In https://github.com/aws/amazon-vpc-cni-k8s/blob/8d05975da4f81274a3307806e5583fc9aa787d43/pkg/ipamd/ipamd.go#L1883 if error occurs in node label update, it needs to return error to the caller.

Instead, it logs the error and continues on to indicate that it updated the node with the label in https://github.com/aws/amazon-vpc-cni-k8s/blob/8d05975da4f81274a3307806e5583fc9aa787d43/pkg/ipamd/ipamd.go#L1885

**Attach logs**

**What you expected to happen**:
 If error occurs in node label update, it needs to return error to the caller.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version 1.10.2
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by M00nF1sh** [comment]
we should consider use TwoWayStrategicMergePatch instead of update. (which saves request payload & we can disable resource version check safely for our use case)

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/76bd7e3fc59a3dffa28397db2991edfd1a5889c7/pkg/targetgroupbinding/resource_manager.go#L503
