### ISSUE TITLE
Can ENIs tags be defined at pod level?

### ISSUE THREAD

**Issue by igreg** [aws/amazon-vpc-cni-k8s#2069]
**What would you like to be added**:

Could ENI tags be defined at the pod level to make tagging more dynamic?
e.g. to set a tag on the ENI that show the name of the pod/deployment that is using the ENI?
It would be nice we could use pod _annotations_ or _labels_ to add tags.

**Why is this needed**:

Having ENIs being tagged with different tags/values would help identify the ENIs used by a specific pod or replicaset.

**Comment by jayanthvn** [comment]
This will need CreateTag permission (existing CNI permission has it) but we are evaluating to remove additional permissions to improve the security posture of aws-node. Along with this DeleteTag permission needs to be added. 

This will incur higher EC2 calls since with PD, pod scale increases 16 times per secondary IP per ENI and the EC2 calls have to made for reach pod create and delete.

**Comment by jayanthvn** [comment]
@igreg - Also on a side note, there is a 50 tags limit per resource (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-tags.html) which we would exhaust with prefix delegation.
