### ISSUE TITLE
Create a readme for cni-metrics-helper charts

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2143]
**What would you like to be added**:
Readme for cni-metrics-helper charts - https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/cni-metrics-helper

Similar to https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/README.md

**Why is this needed**:
Ease of use and better customer experience.

**Comment by 0xquark** [comment]
Hi 👋 @jayanthvn  I would like to work on this issue

**Comment by 0xquark** [comment]
Hi @jdn5126 , Sorry for the delay! Been studying for the end sems lately, Now I'm up for working on the issue.Before writing readme, I wanted to install this chart. I am not sure about which repo has the cni-metrics-helper chart so that i can add it in helm and then install it.Could you help me with that?

**Comment by jdn5126** [comment]
@0xquark no worries, I had some free time the other day but then got pulled into something else. Currently, the chart is only present in this repo at https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/cni-metrics-helper , so that's where the README would go. The helm installation instructions would be to install from that directory, i.e. `helm install cni-metrics-helper ./charts/cni-metrics-helper`

**Comment by jdn5126** [comment]
All env variables should be called out, i.e. `USE_CLOUDWATCH`, `METRIC_UPDATE_INTERVAL`, `AWS_REGION`, `AWS_CLUSTER_ID`, and all fields in https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/cni-metrics-helper/values.yaml .

Bonus points would be adding a `resources` section to the `values.yaml`. https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/README.md is a good reference.
