### ISSUE TITLE
New instance types not supported for trunk ENIs

### ISSUE THREAD

**Issue by barryrobison** [aws/amazon-vpc-cni-k8s#2166]
**What would you like to be added**:

c6in, r6idn, m6idn instances currently do not have the `vpc.amazonaws.com/has-trunk-attached=true` label applied. This means pods requiring Security Groups ( via ENABLE_POD_ENI ) can't be scheduled on them.

**Why is this needed**:

Our AutoScaling Groups use *Instance Requirements* and some AZs are only getting c6in instances.

**Comment by haouc** [comment]
@barryrobison as I responded at [the VPC resource controller repo request ](https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/162), we are updating and releasing latest supported instance types and doing a research to remove the dependence on hard coded file. VPC CNI has nothing to do with how/what the VPC resource controller supports new EC2 instance types. Please let us know if you have any concern on CNI side. Otherwise I will close this ticket and track the update with [the other request](https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/162).

**Comment by barryrobison** [comment]
Great, thanks Hao!
