### ISSUE TITLE
resource limit on init container in eks addon

### ISSUE THREAD

**Issue by pdeva** [aws/amazon-vpc-cni-k8s#2191]
Using latest version of AWS VPC CNI Addon: v1.12.0-eksbuild.1
The default configuration has no resource limit specified for the init container.

The newly added [Addon configuration setting](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/) only allows setting resources for the primary container but not the init container.

**What would you like to be added**:
The addon configuration should allow setting resource limits for the init container too.

**Why is this needed**:
Recommended practice to ensure k8s scheduler can sucessfully schedule pods. Also helps user  to know/control the resource usage of this container.

**Comment by achevuru** [comment]
@pdeva Yes and that is because we currently don't have any resource limits/requests settings in the init container [spec](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L123) in our default manifest. We don't currently specify any limits/reqs because this is not a long running container and CNI will not even move to running state without `init` container successfully completing it's work (and exiting). Node will fail to move to `Ready` state without VPC CNI pod up and running and so we didn't see a need to cap any resources for the init container.

**Comment by jdn5126** [comment]
Closing as fixed by #2205. This will ship in v1.13.0
