### ISSUE TITLE
Requesting for a new ipamd environment variable for running on unschedulable node.

### ISSUE THREAD

**Issue by rajeeshckr** [aws/amazon-vpc-cni-k8s#2265]
**What would you like to be added**:
An environment variable RUN_ON_NON_SCHEDULABLE_NODE on the ipamd defaulted to `false` to not to break existing behaviour.
And consider that along with isNodeNonSchedulable to override the existing behaviour.
```diff
- if c.isNodeNonSchedulable() {
+ if !c.runOnNonSchedulable && c.isNodeNonSchedulable() {
		log.Debug("AWS CNI is on a non schedulable node, not detaching any ENIs")
		return
}
```
**Why is this needed**:
We wanted the CNI pod to run on a non-schedulable node. With c.isNodeNonSchedulable() check, the pod keeps failing on a non-schedulable node. This breaks some of our upstream kubernetes components. 
Please let us know if this does not make sense.

**Comment by jdn5126** [comment]
@rajeeshckr can you expand on the use case here a bit more? The section you highlighted does not control whether the daemonset runs on a non-schedulable node, only whether ENIs will be attached and detached on that node.

**Comment by rajeeshckr** [comment]
Thanks for replying @jdn5126 
You are right, sorry for the confusion. Yes, the daemonset was running on the node. But we were getting these errors for another daemonset because IPAMD was not attaching ENIs any more.
```
  Warning  FailedCreatePodSandBox  3m7s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "61b69b4d92b64679caa050e19490015d280e78a4074d09e2e5bb2e6dc72c0a4d": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  ```
  
 This failing daemonset is a key kube-system component that has the responsibility to signal to ASG that the node is healthy. Since it was not able to set the node healthy, ASG kept on terminating and re-adding instances.
 
 With this flag, user can opt in for this behavior if needed.

**Comment by jdn5126** [comment]
Is that other daemonset not running in host-networking mode? It sounds like the concern is that the non-schedulable node will show up as unhealthy if a pod IP cannot be allocated to this other daemonset. Since the node is unschedulable, I would expect all other pods to be drained and even if this daemonset is not running in host-networking mode, it should get an IP from the primary ENI, which will never be detached. Are there other pods running on this node?

Allocating pod IPs on an unschedulable node seems like a gray area in terms of k8s best practices, so just want to make sure I understand the motivation fully before making any suggestions.

**Comment by rajeeshckr** [comment]
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/6300095/219542629-6880238f-b2bf-47ed-a10a-29b65592583b.png">
Here is our list of daemonsets that are not drained running on that node. The `kube-node-problem-detector-nb4ql` and csi are not running in host networking mode. They are not getting IPs.

**Comment by jdn5126** [comment]
I see. After some thinking, I realized that since we don't detach or attach ENIs while the node is unschedulable, there are cases where this could happen for new pods. Were these pods not running before the node was cordoned? And do you have any reason to run them? Could you force them to be drained with `--ignore-daemonsets=false`?

I think I understand the problem, but I am leaning towards avoiding an environment variable for this case, as it seems to go against k8s best practices, and there are other mechanisms to stop these pods from running on these unschedulable nodes.

**Comment by rajeeshckr** [comment]
kube-node-problem-detector, we need to definitely run. Since that does some health checks on the node.

**Comment by jdn5126** [comment]
I see, I would recommend running that in host networking mode if you really need this to work on an unschedulable node. I think we need to leave this request to a fork approach, as I don't think such an env var is a good idea for VPC CNI to add.

**Comment by adammw** [comment]
Some further context as to our Kubernetes setup...

> it should get an IP from the primary ENI, which will never be detached.

We're running with `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG` therefore the primary interface isn't used at all, and there are 0 IPs available for pods to use until CNI adds a secondary ENI, which never happens if the node is marked for draining before CNI has started up.

> Allocating pod IPs on an unschedulable node seems like a gray area in terms of k8s best practices

From our perspective, it's not necessarily a given that unschedulable == about to shutdown which is where we're hitting this race condition. In terms of the kube-node-problem-detector daemonset mentioned, we explicitly require a CNI-based Pod IP rather than a host network in order for the daemonset to detect problems with pod networking rather than get a bad signal from host networking.

**Comment by jdn5126** [comment]
@adammw I see, that description makes this sound a bit more reasonable. If you can, please submit a pull request for this and we can review it

**Comment by rajeeshckr** [comment]
Thanks @jdn5126 we will get to it soon.
