### ISSUE TITLE
Update to 12.2.2 seems to lose customer settings

### ISSUE THREAD

**Issue by jdnurmi** [aws/amazon-vpc-cni-k8s#2268]
**What happened**:

As part of normal operations, the CNI plugin was updated from v1.12.0-eksbuild.2 to v1.12.2-eksbuild.1 via the AWS EKS API.

The update completed, nominally successfully, but pods that had security groups configured began to fail to launch or started to crash.

After a revert, the behavior continued.

On analysis, it appeared that the 'values' for both ENABLE_POD_ENI and DISABLE_TCP_EARLY_DEMUX had been deleted from the aws-node daemonset configuration (though they continued to be listed such that:

```
- name: ENABLE_POD_ENI
- name: <next config item>
```

Adding those back restored functionality to expected operations on the old version, the update has not been reattempted.

**What you expected to happen**:

Operation would continue as normal or the values would have been fully deleted obviating the difference

**How to reproduce it (as minimally and precisely as possible)**:

Presumably:
- Create a cluster with addon v1.12.0-eksbuild.2 of the CNI
- Set the above options to true
- Create a pod that depends on pod security groups (for testing)
- Update the cluster to v1.12.2-eksbuild.1

**Anything else we need to know?**:

Update was effected by pulumi, and generally we default to 'OVERWRITE' of add-on settings -- likely this was related, though we've never experienced exactly this failure during a CNI add-on update previous to this one.

**Environment**:
- Kubernetes version 1.24
- CNI Version: multiple, see above
- OS (e.g: `cat /etc/os-release`): bottlerocket latest

**Comment by jdn5126** [comment]
@jdnurmi These variables are part of the addon schema for VPC CNI, so when using the managed addon, you have to set them during create or update with:
```
aws eks (create-addon | update-addon) ... --configuration-values  '{"env":{"ENABLE_POD_ENI": "true"}, {"DISABLE_TCP_EARLY_DEMUX": "false"}}'
```
(If the addon was previously created with configuration values, those will be preserved on update as long as `--configuration-values` is not passed)

If you set them manually and then update with `--resolve-conflicts OVERWRITE`, the default values in the new version will be applied. I would suggest not using `--resolve-conflicts OVERWRITE` by default, then adding it only after determining the overwrites are acceptable.

The reason these specific versions/variables are affected is that in v1.12.1+, we started specifying the defaults specifically so that conflicts would be generated and caught, and the behavior would always be deterministic.

**Comment by jdn5126** [comment]
Closing this as it works as expected
