### ISSUE TITLE
[QUESTION] AWS EKS Managed Nodepool with custom CIDR on AWS-CNI in Multi-Zone Multi-AZs

### ISSUE THREAD

**Issue by Moep90** [aws/amazon-vpc-cni-k8s#2279]
**What happened**:
Hey Guys in re:post I asked the following question: [here](https://repost.aws/de/questions/QUiv4poJhHTwGVD8mZQXGv-w/aws-eks-managed-nodepool-with-custom-cidr-on-aws-cni).

.....and also want to spread my question here as I assume that re:post may not have the same range in the repo directly.

**Environment**:
- Kubernetes version (use `kubectl version`): `1.24`
- CNI Version: `v1.12.0-eksbuild.1`
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```
- Kernel (e.g. `uname -a`):
```
Linux ip-[...]internal 5.4.228-131.415.amzn2.x86_64 #1 SMP Tue Dec 20 12:51:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jdn5126** [comment]
Hi @Moep90 , I read through the linked post and I agree with the suggestion there. Since you cannot name your `ENIConfigs` the same as the availability zone that you are using them for, and you want to automate the node selecting the desired `ENIConfig`, you can set `ENI_CONFIG_LABEL_DEF` to labels specific to your node pools, and the controller will automatically get the `ENIConfig` based on the label.

That happens here in the code, if you are curious: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/eniconfig/eniconfig.go#L136

**Comment by Moep90** [comment]
Thx I simply was mislead by several tutorials and guides which always stated to use annotations for that.

**Comment by jdn5126** [comment]
@Moep90 yeah, we definitely recommend annotations first as the most common case is ENIConfig names the same as availability zones
