### ISSUE TITLE
Default WARM_ENI_TARGET causes exhaustion of IP addresses in subnets

### ISSUE THREAD

**Issue by dudicoco** [aws/amazon-vpc-cni-k8s#2294]
Hi,

The IP addresses created by the AWS CNI in our EKS clusters are largely unused (unassigned to pods) which have caused IP exhaustion in some of our subnets a few times.

Here's the graph of unused IP addresses over the last two weeks:
![Screen Shot 2023-02-28 at 17 14 20](https://user-images.githubusercontent.com/51051860/221965347-bd879b3f-3760-462a-a6aa-ab28f99be86e.png)

We're considering adding the WARM_IP_TARGET and MINIMUM_IP_TARGET environment variables per the docs: [https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/eni-and-ip-target.md ](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/eni-and-ip-target.md)

However, the docs warn against doing so as these variables are intended for small clusters, or clusters with very low pod churn, due to the risk of API request throttling.

We're running 250 nodes and 2500 pods in peak traffic and here's a graph of our pods churn:
![Screen Shot 2023-02-28 at 22 11 22](https://user-images.githubusercontent.com/51051860/221967541-1286e004-c1c5-444d-a8bc-ce3917ac5196.png)

I would assume that ours is not a small cluster with a very low pod churn, yet we are experiencing thousands of unused IP addresses.

Can someone advise if this is normal behavior and if so what is the suggested solution that would not cause API throttling in large clusters?

In addition, how can we calculate if indeed adding these env vars will cause throttling?

Thanks

**Comment by jdn5126** [comment]
That is a lot of pod churn, which can lead to pod IPs in cooldown and sparse ENI allocation. When a pod is deleted, its IP goes into cooldown for 30 seconds. When an ENI has no IPs available, but we have IPs in cooldown, we wait until IPs are out of cooldown before attaching more ENIs (since existing allocation can support load).

You may want to set a MINIMUM_IP_TARGET here, so you reserve a minimum set of IPs on each node to handle the scaling up and down. Note that the MINIMUM_IP_TARGET is per node, so the number of IPs reserved would be `num_nodes * MINIMUM_IP_TARGET`. Also, you may want to consider using prefix delegation: https://aws.github.io/aws-eks-best-practices/networking/prefix-mode/

**Comment by dudicoco** [comment]
@jdn5126 i'm a bit confused by your statements.
The docs clearly say NOT to use MINIMUM_IP_TARGET and WARM_IP_TARGET with big clusters/high pod churn due to the risk of throttling, yet you say that these cases are what these vars we designed for.

Regarding the prefix mode, currently i'm only concerned with preserving IP addresses and avoiding throttling, would prefix mode have any effect with these cases?

The unused IP addresses are calculated with total ip addresses - assigned ip addresses (can be see on top of the screenshot in the prometheus query).

**Comment by jdn5126** [comment]
Yes, higher warm/minimum targets can lead to a lot of EC2 API calls, which can lead to EC2 API throttling depending on your account limits. That is definitely a concern here during a fast scale-up or reload event, which is why I think prefix delegation is the better option.

I believe the metric you are using for total IP addresses is multiplying the number of allocated ENIs times the number of IP addresses assigned to those ENIs. Therefore, if your ENIs are sparsely populated (which can happen with pod churn), it is a bit misleading. Now, if you use prefix delegation, when an ENI is attached, we could all IPs in that /28 prefix as "available", so the metric is misleading in that case as well.

**Comment by vanhtuan0409** [comment]
I'm facing this issue as well. To my understanding, when `WARM_ENI_TARGET` is enabled, the cni will not release IP after pod get terminated. The IP keep being attached to network interface without being assigned to any pod, and can be reuse for future pod. Keeping warm IP can avoid the need of provisioning new IP and attach it to the network interface whenever a pod get created

The issue is there are lots of unused IP (IPs that are not assigned to pod). This lead to unable to provision new EC2 instance because the subnet is running out of IP. This can happen in cluster with high pod termination rate

May I know there is any downside from turning off WARM_ENI_TARGET? what is the symptom of having EC2 API throttled?

**Comment by jdn5126** [comment]
@vanhtuan0409 once an ENI is attached, all of those IPs are "allocated" from the subnet and assigned to pods as they are requested. You are correct that an ENI is not released until all pods on it are deleted, making all the IPs available to reclaim.

Depending on the workload, this can lead to an extra ENI being attached, which is why `WARM_IP_TARGET` ends up being more efficient (since it counts IPs available rather than making sure there are always X ENIs attached with no pods assigned). Not setting WARM_ENI_TARGET (or setting it to 0) would not make EC2 API throttling more likely, it would lead to the opposite. The downside is slower average pod startup times.

**Comment by dudicoco** [comment]
@vanhtuan0409 i'm now considering setting `WARM_IP_TARGET` to 0 to solve the IP exhaustion problem, this would free up about half of the unused IP addresses in the subnets and the only downside is an up to 10 seconds delay in new ENI creation when all of the IPs in an ENI are used.

> Yes, higher warm/minimum targets can lead to a lot of EC2 API calls, which can lead to EC2 API throttling depending on your account limits. That is definitely a concern here during a fast scale-up or reload event, which is why I think prefix delegation is the better option.

Can you please elaborate on how prefix delegation would help with this use case?

> I believe the metric you are using for total IP addresses is multiplying the number of allocated ENIs times the number of IP addresses assigned to those ENIs. Therefore, if your ENIs are sparsely populated (which can happen with pod churn), it is a bit misleading.

Can you please explain why this metric is misleading?

**Comment by vanhtuan0409** [comment]
@dudicoco may I know if you have custom config on the cni addons? Because AFAIL, the warm ip target does not set to a value by default (which is equivalent to 0 anyway)

**Comment by dudicoco** [comment]
@vanhtuan0409 I don't have a custom config, sorry i've mistakenly written `WARM_IP_TARGET` instead of `WARM_ENI_TARGET` in my last comment.

I'm considering changing `WARM_ENI_TARGET` from the default value of 1 to 0, i've tested this in a small cluster and it indeed reduces the number of unused IP addresses in the subnets.

**Comment by vanhtuan0409** [comment]
Oh I also changed it to 0 on cluster with high node termination rate. So far no serious problem occured
