### ISSUE TITLE
VPC CNI defaults to v1.11 for K8s v1.24 clusters

### ISSUE THREAD

**Issue by dgoswami75** [aws/amazon-vpc-cni-k8s#2357]
**What would you like to be added**: VPC CNI defaults to v1.11 for K8s v1.24 clusters, when it should be v1.12.

**Why is this needed**: Causes errors due to dockershim being removed in K8s 1.24. According to https://github.com/aws/amazon-vpc-cni-k8s/releases, the recommendation is that VPC CNI needs to be at least v1.12, so why default to a wrong version at creation time?

**Comment by jdn5126** [comment]
@dgoswami75 the default VPC CNI addon version for EKS 1.24 is `v1.11.4`. The default addon version is set during the EKS 1.24 launch and it **cannot** be changed after launch. Otherwise, customers creating/re-creating clusters in the future would have different addon versions.

The latest addon version is the recommended version, and if you want that to be installed during cluster creation, you can specify it. For `eksctl`, see https://eksctl.io/usage/addons/#setting-the-addons-version

**Comment by jdn5126** [comment]
Closing this issue as the behavior works as expected
