### ISSUE TITLE
503 for Daemonset using hostPort on EKS

### ISSUE THREAD

**Issue by satyamab** [aws/amazon-vpc-cni-k8s#2362]
**What happened**:

I have a daemonset listening on hostport 8126 that most pods talk to in order to send trace data. On some of the pods we see connection errors like 

```
failed to send, dropping 3 traces at http://10.229.152.170:8126/v0.5/traces after 3 retries ([Errno 104] Connection reset by peer), 11 additional messages skipped
```

When I do a `cilium sysdump` and look at the iptables I see multiple entries for port `8126` and one of them points to a pod that no longer exists as below. 

```
[0:0] -A CNI-DN-3ffc3410c219971c3097e -s 10.229.155.6/32 -p tcp -m tcp --dport 8126 -j CNI-HOSTPORT-SETMARK
[0:0] -A CNI-DN-3ffc3410c219971c3097e -s 127.0.0.1/32 -p tcp -m tcp --dport 8126 -j CNI-HOSTPORT-SETMARK
[0:0] -A CNI-DN-3ffc3410c219971c3097e -p tcp -m tcp --dport 8126 -j DNAT --to-destination 10.229.155.6:8126

[0:0] -A CNI-DN-4f8ad0af0057a61957791 -s 10.229.154.155/32 -p tcp -m tcp --dport 8126 -j CNI-HOSTPORT-SETMARK
[0:0] -A CNI-DN-4f8ad0af0057a61957791 -s 127.0.0.1/32 -p tcp -m tcp --dport 8126 -j CNI-HOSTPORT-SETMARK
[958177:57490620] -A CNI-DN-4f8ad0af0057a61957791 -p tcp -m tcp --dport 8126 -j DNAT --to-destination 10.229.154.155:8126

[958177:57490620] -A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"aws-cni\" id: \"ebf6f0c823f3c321fe2cf6d91b7d21e429af7eb5d875f45434cc99ec2a1500b9\"" -m multiport --dports 8126 -j CNI-DN-4f8ad0af0057a61957791

[0:0] -A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"aws-cni\" id: \"df9acf2c3cf51b8d440ee144e0ed7e35931994913716e1daea8a65a105ecd558\"" -m multiport --dports 8126 -j CNI-DN-3ffc3410c219971c3097e

```

The IP `10.229.155.6/32` is allocated to another pod from another deployment so its not even listening on port 8126. Is this expected and possibly the reason behind the errors? I have seen issues like [this](https://github.com/containernetworking/plugins/issues/683) which seem to suggest it may be a portmap CNI issue which I believe aws-cni packages in. 

I am no networking expert so looking for some guidance incase we have misconfigured something with aws-cni or if this is a known unresolved issue? Thank you!

**Environment**:
- Kubernetes version (use `kubectl version`): v1.23.17-eks-ec5523e
- CNI Version: 1.12.6
- OS (e.g: `cat /etc/os-release`): AmazonLinux v2
- Kernel (e.g. `uname -a`): 5.4.228-132.418.amzn2.x86_64

We are using cilium 1.12.8 with CNI chaining to aws-cni.

**Comment by jdn5126** [comment]
@satyamab this does seem to line up with https://github.com/containernetworking/plugins/issues/683 . As you said, aws-node pod does package portmap plugin (currently v1.2.0), but there does not appear to be a fix in any portmap version.

If you want to use cilium, I don't recommend chaining it with the VPC CNI. I would recommend just using one or the other, as chaining adds too much overhead and complexity for no benefit.

**Comment by jdn5126** [comment]
@satyamab it also might be worth asking on that issue to have it reopened

**Comment by satyamab** [comment]
Thanks for the quick response @jdn5126, much appreciated! I have asked on the issue.

Also thank you for the guidance on the chaining. We will definitely have a look into that. Would you be able to provide any pointers on what the overhead might be and the potential implications of it please? Keen to understand the detail a bit more!

**Comment by satyamab** [comment]
Also would it be fair to say this would affect us even if we were not using cilium and using aws-cni only? Since `hostPort` functionality is provided by the portmap plugin?

**Comment by jdn5126** [comment]
Chaining is what adds the overhead, as every networking request would chain from AWS VPC CNI to Cilium CNI. Not chaining means requests go only to Cilium CNI (and AWS VPC CNI is not running). The downside of this is that Cilium CNI does not support as many features on EKS as the native AWS VPC CNI.

I assume you followed https://docs.cilium.io/en/v1.13/installation/cni-chaining-aws-cni/ to chain the AWS VPC CNI and Cilium? That page does seem to have a link to a video discussing how to migrate fully to Cilium.

But back to the issue, the main question is why to use Cilium here in the first place. Chaining AWS VPC CNI with Cilium is something that Cilium claims to support (AWS does not), but I do not see much upstream documentation or information on how they do testing. AWS is definitely not testing every new VPC CNI release in Cilium chaining mode.

This issue is specific to the Cilium chaining, and does not apply to using AWS VPC CNI only.
