### ISSUE TITLE
Uninstalling calico breaks networking

### ISSUE THREAD

**Issue by kart2** [aws/amazon-vpc-cni-k8s#2385]
By using tigera-operator helm chart I installed calico version https://artifacthub.io/packages/helm/projectcalico/tigera-operator/3.25.0.

**What happened**:
All of a sudden, the eks workloads connectivity was failing.
Noticed typha, calico-kube-controller readiness was also failing.

**Attach logs**

**Anything else we need to know?**:

I tried to uninstall calico in order to reset the calico rules. But it looks like i have to recreate all the nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24
- CNI Version - 3.25.0
- OS (e.g: `cat /etc/os-release`): amazon ami

How to upgrade or downgrade calico? 
Does a migration to older version via helm breaks the node network?

**Comment by jdn5126** [comment]
@kart2 using the Calico CNI on EKS requires you to remove the AWS VPC CNI: https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks

Also, uninstalling Calico will not clean up the node iptables rules that Calico installed, which is why you had to reload all of the nodes.

I suggest you reach out to Calico support or file an issue on their repo, as this is unrelated to AWS VPC CNI.

**Comment by jdn5126** [comment]
Closing this issue as it is not related to AWS VPC CNI
