### ISSUE TITLE
IP release feature 

### ISSUE THREAD

**Issue by nicoaws** [aws/amazon-vpc-cni-k8s#2460]
To improve the utilisation of IPv4 ranges I think the AWS CNI should implement a feature like the “release IP” in Cilium.

https://docs.cilium.io/en/latest/network/concepts/ipam/eni/

I see this scenario often:

I run AWS CNI with prefix delegation:

1. IP range with 16 IPs assigned to the node
2. The 17th pod is scheduled, so an additional range is assigned (ignoring warm prefix, the logic works with and without)
3. Some of the original pods are descheduled
4. The node is left with say, 10 pods and two CIDRs assigned to it, using up 32 IPs

I’d like the AWS CNI to be able to deschedule pods that are inefficiently packing.

**Comment by Alex-Waring** [comment]
Hi @jdn5126 , to pick up on this can we request it as a feature we can toggle? I know it would be very disruptive but the current situation really isn't great.

**Comment by jdn5126** [comment]
@Alex-Waring you can file an EKS Containers Roadmap Feature Request: https://github.com/aws/containers-roadmap/issues to provide a better solution for handling sparsely populated ENIs, and the amount of community upvotes will help in prioritizing working on a solution. This problem is something we should try to solve, but I do not think packing is the right solution.

**Comment by jdn5126** [comment]
> Thanks @jdn5126, I will do. Before I do, do you have a recommended solution or should I just highlight the problem

Not currently, sorry. Other than the CNI supporting a new mode with a non-ENI-based architecture

**Comment by Alex-Waring** [comment]
https://github.com/aws/containers-roadmap/issues/2071
