### ISSUE TITLE
Custom networking different behaivor with v1.13 and v1.11

### ISSUE THREAD

**Issue by hitsub2** [aws/amazon-vpc-cni-k8s#2490]
With v1.11.4-eksbuild.1, when enabled AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true, if the node is not annotated with enifconfig, pods assigned to the node will be pending, which is expected. But with v1.13.4 version, the pod is running, which is not expected.

Is that expected in v1.13.4?

**Comment by jayanthvn** [comment]
We should have seen aws-node init fail if the `eniconfig` is missing since in 1.13.4 we try to allocate IP but on startup expectation is only primary ENI is present so we skip it for custom networking and then we try allocate ENI which should fail here - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.13.4/pkg/ipamd/ipamd.go#L891

Then we have additional check https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.13.4/pkg/ipamd/ipamd.go#L605 which would have failed because DS is empty and aws-node init would have failed.

But did you ensure nodes were terminated before enabling custom networking on v1.13.4? Or was this an upgrade from 1.11.4 to 1.13.4 with custom networking enabled? You mentioned pods are running, were those pods on primary ENI or did you notice a secondary ENI? Can you upload the logs or email those to`k8s-awscni-triage@amazon.com`
