### ISSUE TITLE
SNAT for private subnet

### ISSUE THREAD

**Issue by balu-ce** [aws/amazon-vpc-cni-k8s#2523]
The k8s cluster nodes is running in a private subnet and iam enabling snat in vpc cni to true. will the outgoing traffic will have elastic ip attached to the route table of the subnet or it will assigned from eni

**Comment by jdn5126** [comment]
@balu-ce we are going to need a lot more information here. What does "IAM enabling SNAT in VPC CNI to true" mean? Are you referring to the `AWS_VPC_K8S_CNI_EXTERNALSNAT` environment variable.

Which elastic IP are you talking about? Which VPC CNI version are you using?

In general, the source IP for pod traffic is the pod IP if the destination is in the VPC, otherwise it is SNAT to the node IP. When `AWS_VPC_K8S_CNI_EXTERNALSNAT` is set, the source IP is always the pod IP.

**Comment by balu-ce** [comment]
@jdn5126 yes I am reffering to AWS_VPC_K8S_CNI_EXTERNALSNAT=true .  

But mine is private subnet which has private ip attached to the pod, In that case how it behaves,

1. will it go via nat gateway attached to our private subnet ?
2. Then if I hit a external world call from pod then the source ip will be pod ip ?
3. Also It is only the security advantage we are getting through SNAT enabling or any other application use cases

**Comment by jdn5126** [comment]
All pod IPs are private VPC IPs. Setting `AWS_VPC_K8S_CNI_EXTERNALSNAT` to true says "do not do SNAT on the node as it will happen elsewhere in the VPC", which in your case would be the NAT gateway. The routing path depends on the traffic flow and your VPC configuration.

This is not really a VPC CNI issue, so I suggest opening a support case to get some help and clarity with your configuration.

**Comment by jdn5126** [comment]
Closing due to lack of information to triage
