### ISSUE TITLE
WARM_ENI_TARGET is 1. But worker node ENI 2 (with coredns pods used)

### ISSUE THREAD

**Issue by itjobs-levi** [aws/amazon-vpc-cni-k8s#2857]
**What happened**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.29
- CNI Version : v1.16.4-eksbuild.2
- OS (e.g: `cat /etc/os-release`): amazon linux 2023
- Kernel (e.g. `uname -a`): 

---

**Problem scenario**:

I have no deployments on the worker node.
Since WARM_ENI_TARGET is set to 1, I thought the worker node would have one ENI.
(WARM_IP_TARGET not used)

However, worker nodes have two ENIs by default.

Running pods are aws-node, coredns*2, eks-pod-identity, and kube-proxy.

I suspected the coredns pod.

So, I created another worker node.
At this time, there was only one ENI, and only aws-node, eks-pod-identity, and kube-proxy pods were running.

Then, I killed one coredns and moved it to the newly created worker node.

the worker node also had two ENIs.

Is this normal behavior?

**Comment by jchen6585** [comment]
Hi! Yes this behavior is normal. `WARM_ENI_TARGET=1` means VPC-CNI will keep one extra ENI (with max IPs allocated) ready to be used. The reason you saw two ENIs is because coredns pods do not use the host IP. Rather, they get an IP from an ENI. Since the primary ENI no longer has max IPs, VPC-CNI will spin up another ENI (with max IPs allocated).
