### ISSUE TITLE
Should node agent be opt-in on vpc CNI

### ISSUE THREAD

**Issue by AbeOwlu** [aws/amazon-vpc-cni-k8s#2897]
**What happened**: node agent failed start caused aws-node cni issues on worker node

[Issue regarding occurrence reported here](https://github.com/aws/aws-network-policy-agent/issues/260)

**Comment by orsenthil** [comment]
Network Policy is a Feature of CNI,which is disabled by default. The agent is installed with the CNI so that anytime a customer wants to enable, they can update the configuration have the feature of Network Policy. The node agent failure to start should be a separately tracked issue as you have raised it in the node-agent repo.
