### ISSUE TITLE
 ENI is deleted but ipamd daemon still think it's active

### ISSUE THREAD

**Issue by Jeffwan** [aws/amazon-vpc-cni-k8s#307]
ipamd daemon is restarting with following error:

```
2018-11-30T18:49:08Z [ERROR] Failed to get eni eni-xxxx information from EC2 control plane InvalidNetworkInterfaceID.NotFound: The networkInterface ID 'eni-xxxx' does not exist
	status code: 400, request id: 3036f11e-e1b7-4702-a0ab-866
```

Found in the logs that this ENI was already deleted but ipamd daemon was getting this eni as active and attached to index:8 and hence this error. From logs it looks like this error is crashing the ipamd daemon and since restart policy of that pod is `Always`, it restarts but still get same error. 

Since ENI is deleted and I notice there's a PR #194 trying to address this issue. But seems that's not the elegant way and may swallow other messages.

**Comment by nak3** [comment]
The root cause would be same with https://github.com/aws/amazon-vpc-cni-k8s/pull/194 but it looks like you are getting error different timing when ipamd calls `FreeENI()`.

Hence, the logs is showing the [InvalidNetworkInterfaceID.NotFound](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html) error code, which is quite easily filtered. Furthermore, Free ENI operation would be skipped optimistically if ENI is NotFound unlike https://github.com/aws/amazon-vpc-cni-k8s/pull/194.

I have sent https://github.com/aws/amazon-vpc-cni-k8s/pull/310. WDYT @Jeffwan ?

**Comment by Jeffwan** [comment]
Thanks! I think it should be good to resolve this issue.

**Comment by mogren** [comment]
I have [a related PR open](https://github.com/aws/amazon-vpc-cni-k8s/pull/308/files#diff-3fbbb0bd392fd47bd85a56d6221de538R419) to log the `awsClient.FreeENI(eni)` error that we used to ignore.
