### ISSUE TITLE
Is there an overhead introduced by the Amazon VPC CNI plugin for EKS on the MTU (Maximum Transmission Unit)

### ISSUE THREAD

**Issue by gsustek** [aws/amazon-vpc-cni-k8s#3085]
If i set :
AWS_VPC_ENI_MTU = 1500

how much i need to set 
POD_MTU = ?

Does this calculation applies?
Effective MTU = Default MTU - VXLAN Overhead

Sorry for question,
is even  an AWS VPC CNI is an overlay network?

**Comment by orsenthil** [comment]
Is AWS VPC CNI is an overlay network?

No, it is not an overlay network plugin.

**Comment by orsenthil** [comment]
As answered, AWS VPC CNI is not an overlay plugin. VXLAN and VXLAN Overhead doesn't come into picture.

The POD_MTU was supported when customers tried to use Cilium with Wireguard as chain plugin with VPC CNI (before VPC CNI supported Network Policy). When customers ran into this and requested for the ability set MTU at pod level (because cilium wireguard extension was using overlay and providing Network Policy), it was introduced as support here - https://github.com/aws/amazon-vpc-cni-k8s/issues/2606

If you are only using VPC CNI, you don't need set POD_MTU and it will default to AWS_VPC_ENI_MTU. 

Hope this clarifies.
