### ISSUE TITLE
cni-metrics-helper CLUSTER_ID

### ISSUE THREAD

**Issue by groodt** [aws/amazon-vpc-cni-k8s#313]
How do modify the cni-metrics-helper CLUSTER_ID? Right now, it seems to be fixed at `eks-cluster`. This is also the only id mentioned in the cni-metrics-helper blog post.

This isn't very useful if I have multiple EKS clusters and wish to monitor different clusters for available ENI and IP address capacity.

**Comment by nak3** [comment]
cni-metrics-helper-xxxx's logs output `Failed to obtain cluster-id and default to eks-cluster`?

e.g:
```
$ kubectl -n kube-system logs cni-metrics-helper-xxxx
...
           publisher.go:76] Failed to obtain cluster-id and default to eks-cluster
```

If yes, cni-metrics-helper is using same code with https://github.com/aws/amazon-vpc-cni-k8s/pull/88/files

You can configure `CLUSTER_ID` by following steps:

#### 1. Add policy to __worker__ Node's policy like:

```
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeTags"
            ],
            "Resource": [
                "*"
            ]
        }
```

#### 2. you can modify the value of `CLUSTER_ID` for EC2 instance as:

- KEY:   CLUSTER_ID
- VALUE: <YOU CAN SET YOUR VALUE>


#### 3. Restart `cni-metrics-helper-xxxx` pod.

- Please also check if you are getting `Failed to obtain cluster-id and default to eks-cluster` or not.

```
  $ kubectl -n kube-system delete cni-metrics-helper-xxxx
  $ kubectl -n kube-system logs cni-metrics-helper-xxxx  
```

Now, you should be able to see the modified `CLUSTER_ID` instead of `eks-cluster`.

**Comment by groodt** [comment]
@nak3 Looks like you are right. I see this in the logs:
```E0207 12:22:48.352171       7 publisher.go:76] Failed to obtain cluster-id and default to eks-cluster```

I'll try the tags as you suggest and report back.

**Comment by groodt** [comment]
That worked like a charm. Thanks @nak3 

I'll close this issue.
