### ISSUE TITLE
Document how to determine IAM role permissions issues

### ISSUE THREAD

**Issue by mentalisttraceur** [aws/amazon-vpc-cni-k8s#389]
`aws-node` daemonset enters `CrashLoopBackoff` state when the EC2 instance lacks the necessary IAM role without giving any indication of what the problem is in the logs.

**Comment by jaypipes** [comment]
@mentalisttraceur apologies for the long delay in responding here. How do you determine that the reason the daemonset goes into CrashLoopBackoff is due to improper IAM role permissions? I presume we can trap for the permissions failure and log a warning, etc, but I'd like to understand how you are determining this problem at the moment (given, as you say, there are no log messages indicating the IAM role permissions error).

**Comment by mentalisttraceur** [comment]
@jaypipes When we just added an IAM role with the right permissions to the EC2 instance, and made no other changes, the daemonset stopped crashing.

**Comment by jaypipes** [comment]
@mentalisttraceur can you provide a snippet of your logs before and after adding the IAM role so that we can determine what is not being logged or reported as an error? Thanks!

**Comment by jaypipes** [comment]
The deliverable here is to test specifically what happens when you deploy the aws-node daemonset and have improper IAM role permissions. We need to document what this looks like from the k8s user perspective, how to dig into the pod logs to determine it is an IAM permission issue.

**Comment by jayanthvn** [comment]
As part of #1520 we can update the documentation.
