### ISSUE TITLE
ENI allocation takes lots of time if i brough 100's of nodes at the same time. WARM_ENI_TARGET does not help.

### ISSUE THREAD

**Issue by Deepak1100** [aws/amazon-vpc-cni-k8s#405]
Cluster autoscaler have brought 150 nodes at the same time as I have increased the pods replicas. which resulted in the various container being in container creating state. it took 15 mins for all container to starts.

in this case, WARM_ENI_TARGET does not help as its keep additional eni for individual nodes(over here its old node) and my new node doesn't have any eni. Can't we keep some flag from which vpc-cni create additional eni but unattached to any instance? incase new instance come up they will use that unattached enis

**Comment by nckturner** [comment]
Agreed, this is important: https://github.com/aws/amazon-vpc-cni-k8s/issues/420.  15 minutes is exceptionally long though, were they actually scheduled that whole time?  Do you have any logs from that time?

**Comment by nckturner** [comment]
Its possible you were throttled by EC2 when the 150 nodes launched.

**Comment by Deepak1100** [comment]
yes, I have 5 of these metrics.
```
error="allocate ip address: failed to allocate a private IP address: RequestLimitExceeded: Request limit exceeded. status code: 503, request id: 5b028d54-4b1a-48de-b033-bbcf4749cdb2",fn="retryAllocENIIPAllocAllIPAddressFailed"```
hence I requested the central warm pool of eni from where daemonset just pick them up insisted of creating new eni and assigning ip's. because . it will not work when u created 100s of instance at the same time

**Comment by jaypipes** [comment]
@Deepak1100 apologies for the delay in responding here. After chatting with @mogren, we are not going to attempt to add this feature to the 1.x series of the CNI plugin, and instead are targeting the 2.0 CNI plugin for this functionality. You can read here about the 2.0 CNI plugin design: https://github.com/aws/containers-roadmap/issues/398

You will note that the new design uses a CIDR-allocation strategy instead of a one-by-one IP/ENI allocation strategy. This will essentially alleviate the rate-limiting issues that the original design has.
