### ISSUE TITLE
1.4.0 breaks CloudWatch CNI Metrics 

### ISSUE THREAD

**Issue by guillaume-eb** [aws/amazon-vpc-cni-k8s#409]
I don't see any error in the `cni-metrics-helper` pod logs,  but Cloudwatch stopped gettings metrics at 10:15 in the screenshot below

```
I0424 11:29:32.263814       8 wesley-k8s-metrics.go:127] Collecting metrics ...
I0424 11:29:32.263833       8 discovery.go:118] GetCNIPods start...
I0424 11:29:32.263862       8 discovery.go:127] GetCNIPods discovered[aws-node-fg2d5...
I0424 11:29:32.264068       8 metrics.go:404] Grab/Aggregate metrics from aws-node-fg2d5
I0424 11:29:32.264073       8 cni_metrics.go:99] Grabbing metrics from CNI aws-node-fg2d5
```
 
<img width="1233" alt="Screenshot 2019-04-24 13 24 11" src="https://user-images.githubusercontent.com/31934992/56656080-d8ccbc80-6694-11e9-8132-d42a92f94397.png">

**Comment by mogren** [comment]
Hey @guillaume-eb, thanks for reporting this!

I closed the old PR for #113 and opened #413 instead. We changed the names of the prometheus endpoints in v1.4.0 (PR #348), but since the code for the CNI metrics agent was just in a branch in Liwen's fork, we missed updating it. 

I'll cherry-pick the config back to the release-1.4 branch once the #413 has been reviewed and merged.
