### ISSUE TITLE
Document release policies and practices

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#685]
We should document our policies for when we will cherry-pick patches to a past release branch, what our release gating criteria are, and what our actual release processes are.

**Comment by jaypipes** [comment]
related: #679

**Comment by mmcaya** [comment]
Moving comments from duplicate issue created prior to discovering this issue: 

**What would you like to be added**:

Document the explicit versioning policy and release criteria for both the CNI and calico components of this project. 
It is unclear if the `<major>.<minor>.<revision> ` schema is explicitly semver 2, or just a project specific pattern.
It is also unclear if there is any concrete dependencies or compatibility requirements between the CNI and calico components vended under the same release versions.
Also, it would be helpful to  provide more detailed upgrade guides when major component changes occur in the project.

**Why is this needed**:
The recent 1.7.9 release included the migration of calico management to the tigera operator introduced what a consumer could consider a backwards compatibility breaking change.   [See pull request for reference](https://github.com/aws/amazon-vpc-cni-k8s/pull/1297) 

The PR notes call out some but not all of the changes that would qualify this as containing backwards compatibility breaks.

- New namespace creation requirements in default setup (`tigera-operator`, `calico-system`) outside the traditionally used `kube-system` by the previous calico version.
- Expansion of K8S RBAC from generally read only policies, and limited management of `crd.projectcalico.org` CRDs to full management of multiple resources cluster wide (including secrets)
- CRDs migrated to use `apiextensions.k8s.io/v1` introduced in K8S 1.16, but as 1.15 EKS/K8S clusters are still officially supported by AWS, this could be compatibility issues with 1.15 clusters using only `apiextensions.k8s.io/v1beta1`
- Rollback to previous version difficult or not possible as per PR comments:

> Will this break upgrades or downgrades. Has updating a running cluster been tested?:
Because of the way the upgrade will happen with the operator there is a problem upgrading on a small cluster, 3 nodes or less. This is because for 3 nodes or less the operator tries to deploy a typha for each node and the current calico install uses at least one typha and multiple typhas cannot run on a single node.
Once a cluster is upgraded with these changes, it will not be simple to downgrade back to a versions of Calico that was installed without the operator.

The [CHANGELOG.md](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md#v179) only notes this as an "Improvement", with no immediate indication how that is defined in the context of these projects.    With the changes noted, it would be tremendously helpful to also provide a more explicit upgrade guide for these cases.

AWS Official EKS Documentation has  [previously noted](https://github.com/awsdocs/amazon-eks-user-guide/blob/81968d56d5a5bda27a9456331b3ab37ac22e8304/doc_source/calico.md) using the cni project release branch for directly applying changes, so consumers who have processes or automation not currently pinned to a specific fix revision (e.g. 1.7.5) will receive these type of larger changes that may fall outside their expectations based on their understanding of the versioning scheme.

Example from noted docs previous recommendation: `kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/calico.yaml`

I understand that the method by which manifests are vended will be changing as noted in [this PR](https://github.com/aws/amazon-vpc-cni-k8s/pull/1271), but I hope this request is considered relevant to both the current state (as long as that is maintained) and the new process being adopted.

**Comment by haouc** [comment]
Hello everyone
if you still have concerns, please be aware of our latest announcement. Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version.

All suggestions about our documentation on Calico installation, upgrading or deletion are welcome. Please feel free to send questions to our triage email ([k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)).

If you need migrate Calico from non-operator based installation to operator based installation, we recommend you to check [this Tigera document](https://projectcalico.docs.tigera.io/maintenance/operator-migration). 
If you need upgrade you calico operator but you didn't install Calico via helm, you can check [this Tigera document](https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart). Please being aware that any customized installation may encounter compatibility issue during upgrading.
If you have any issues or questions during Calico resources installation/upgrading/deletion, please refer to the [README](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and send request to Calico repositories.

I am closing this ticket due to unsupported charts upgrade. Again please feel free to reach out to us at ([k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)).
