### ISSUE TITLE
ipamd uses and deletes user-managed ENIs

### ISSUE THREAD

**Issue by euank** [aws/amazon-vpc-cni-k8s#725]
We have a use-case that I can't figure out how to get working safely while using the aws-vpc-cni-eks-k8s-eni plugin.

### Issue

We have a service that we wish to run in host networking and have listen on a public IP with a specific security group. Previously (before using this project), we managed this by associating an ENI with a public IP and the right security group, and that worked well. This service can't be modeled adequately with k8s's networking primitives, so it's necessary we keep doing this same thing, even in the k8s world.

If we try to do the same thing while using the aws-vpc-cni-eks-k8s-eni plugin, we find that this ENI has its secondary IPs used for other pods (not great), and if we drain pods it sometimes is detached from the node and deleted, even though we were the ones to create it (even worse).

### Proposed solution

The solution that makes sense to me is to allow a user of this plugin to denote certain ENIs as being "unmanaged" by this plugin. It then becomes the user's responsibility to configure that ENI and use it as they will.

Is there already a way to accomplish this somehow? Is this a use-case that is in-scope of this project to support?

**Comment by jaypipes** [comment]
I like the concept of being able to reserve ENIs (or elastic IPs, frankly) for a workload that is either not managed by Kubernetes (but running on a k8s worker node) or using host networking and/or specialized offloads or networking capabilities.

I'll take a gander at your PR. Looks promising from an initial skim.

**Comment by mogren** [comment]
@euank You are correct in that this CNI assumes that it owns all ENIs on the node, and currently there is no way for the user to configure this. Tagging the ENIs that you want to be left alone sounds good. I'll take a look at the PR, thanks a lot for working on this!

My only concern so far is that just like when using custom networking, the `--max-pods` value in the default EKS AMI will no longer be correct, since it assumes all ENIs are available and all secondary IPs on them can be used for pods. Also, does this work correctly if the primary ENI is tagged? The CNI will use the private IP of the first ENI for doing SNAT of traffic going outside the cluster.

**Comment by euank** [comment]
> My only concern so far is that just like when using custom networking, the --max-pods value in the default EKS AMI will no longer be correct

Indeed. I think it's up to the user to configure that if they plan to reserve ENIs unless we can think of a better option.

> Also, does this work correctly if the primary ENI is tagged?

I don't think it would, but I think it's reasonable to document the primary ENI for the instance as being special (it is used for the k8s nodeIP after all).

Speaking of, the PR I created is missing all documentation, which I think would be the place to resolve both of those concerns.

**Comment by mogren** [comment]
@euank Totally agree! 🙂

**Comment by mogren** [comment]
Fixed in #726
