### ISSUE TITLE
Add kustomization.yaml to calico yamls

### ISSUE THREAD

**Issue by rdubya16** [aws/amazon-vpc-cni-k8s#833]
Would someone be able to add a kustomization.yaml to the calico manifests stored in this repo so they can be remotely included? 

Example
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/breakfast.md

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

**Comment by jayanthvn** [comment]
Calico installation is currently supported by helm charts (https://github.com/aws/eks-charts/tree/master/stable/aws-calico). Kustomize is not yet supported in CNI.

**Comment by joebowbeer** [comment]
Are these the sought-after calico manifests?

https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config/v1.8

Instructions for installing from manifests:

https://docs.aws.amazon.com/eks/latest/userguide/calico.html

**Comment by haouc** [comment]
@joebowbeer 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
