### ISSUE TITLE
Clarification of WARM_IP_TARGET and MINIMUM_IP_TARGET

### ISSUE THREAD

**Issue by js-timbirkett** [aws/amazon-vpc-cni-k8s#853]
I've been reading all the discussions on the PRs and release notes related to `MINIMUM_IP_TARGET` and am still a bit fuzzy on some things.

Should `MINIMUM_IP_TARGET` be set to the target number of pods on a worker node? or the number of IPs a particular instance type can have on it? 

How does this work in cases where you have multiple worker groups of different instance sizes? Should `MINIMUM_IP_TARGET` be set to the limit of the smallest instance? Does it limit how many pods an instance could run?

**Comment by SaranBalaji90** [comment]
(adding my notes by reading through the code, might need extra pair of eyes to verify my notes)

MINIMUM_IP_TARGET guarantees minimum number of IPs provisioned on the worker node (these IPs can either be used by Pods or stay in the pool as available) where as WARM_IP_TARGET number guarantees those many IPs are available in the pool all the time.

> Should MINIMUM_IP_TARGET be set to the target number of pods on a worker node? or the number of IPs a particular instance type can have on it?

Setting it to number of IPs a particular instance type supports, will pre-allocate those many IPs on your worker nodes. Sometimes this is not recommended, since this might take up all available IP space in your VPC even though number of pods running on the instance might be less.

> How does this work in cases where you have multiple worker groups of different instance sizes?
 
These field is common across your worker nodes. for eg: if all worker nodes will run atleast 10 pods then setting this to 10 will make sure 10 IPs are available on the nodes all the time.

> Should MINIMUM_IP_TARGET be set to the limit of the smallest instance?

Let's say you have, t2.large and t2.micro which supports upto 36 and 4 IPs respectively. Setting 
MINIMUM_IP_TARGET  to 10 will provision all 4 IPs in t2.micro where as it will provision 10 in t2.large. In this case, if you set WARM_IP_TARGET to 2 then it will make sure there are always 2 IPs available in both the nodes.

> Does it limit how many pods an instance could run?
This doesn't limit the pod count. Let me know if you are unsure about this. I can explain.

**Comment by mogren** [comment]
Thanks for the explanation Balaji. In short, it's the "floor" of how many IPs will be around on each node. If you plan to run around 10 pods, I would suggest to set `MINIMUM_IP_TARGET` to slightly higher than that, maybe 12, and have `WARM_IP_TARGET=2` Some example cases:

| Instance type | `WARM_ENI_TARGET` | `WARM_IP_TARGET` | `MINIMUM_IP_TARGET` | Pods | Attached  ENIs | Attached  Secondary IPs | Unused IPs | IPs per ENI |
|---------------|:-----------------:|:----------------:|:-------------------:|:----:|:--------------:|:-----------------------:|:----------:|:-----------:|
| t3.small      |         1         |         -        |          -          |   0  |        1       |            3            |      3     |      3      |
| t3.small      |         1         |         -        |          -          |   5  |        3       |            9            |      4     |    3,3,3    |
| t3.small      |         1         |         -        |          -          |   9  |        3       |            9            |      0     |    3,3,3    |
|               |                   |                  |                     |      |                |                         |            |             |
| t3.small      |         -         |         1        |          1          |   0  |        1       |            1            |      1     |      1      |
| t3.small      |         -         |         1        |          1          |   5  |        2       |            6            |      1     |     3,3     |
| t3.small      |         -         |         1        |          1          |   9  |        3       |            9            |      0     |    3,3,3    |
|               |                   |                  |                     |      |                |                         |            |             |
| t3.small      |         -         |         2        |          5          |   0  |        2       |            5            |      5     |     2,3     |
| t3.small      |         -         |         2        |          5          |   5  |        2       |            7            |      2     |    3,3,1    |
| t3.small      |         -         |         2        |          5          |   9  |        3       |            9            |      0     |    3,3,3    |
|               |                   |                  |                     |      |                |                         |            |             |
| p3dn.24xlarge |         1         |         -        |          -          |   0  |        1       |            49           |     49     |      49     |
| p3dn.24xlarge |         1         |         -        |          -          |   3  |        2       |            98           |     95     |    49,49    |
| p3dn.24xlarge |         1         |         -        |          -          |  95  |        3       |           147           |     52     |   49,49,49  |
|               |                   |                  |                     |      |                |                         |            |             |
| p3dn.24xlarge |         -         |         5        |          2          |   0  |        1       |            5            |      5     |      5      |
| p3dn.24xlarge |         -         |         5        |          2          |   3  |        1       |            5            |      2     |      5      |
| p3dn.24xlarge |         -         |         5        |          2          |  10  |        1       |            12           |      2     |      12     |
|               |                   |                  |                     |      |                |                         |            |             |


To be extra clear, only set `WARM_IP_TARGET` for small clusters, or clusters with very low pod churn. It's also advised to set `MINIMUM_IP_TARGET` slightly higher than the expected number of pods you plan to run on each node.

The reason to be careful with this setting is because it will increase the number of EC2 API calls that ipamd has to do to attach and detach IPs to the instance. If the number of calls gets too high, they will get throttled and no new ENIs or IPs can be attached to any instance in the cluster. 

That is the main reason why we have `WARM_ENI_TARGET=1` as the default setting. It's a good balance between having too many unused IPs attached, and the risk of being throttled by the EC2 API.

**Comment by manideepl** [comment]
I'm sorry to post on a closed issue, but can someone point me to the default WARM_IP_TARGET for different instance types?
Is there a list? I'd like to see it for m5.4x large

**Comment by mogren** [comment]
@manideepl The default is "one ENI", so it depends on the number of [Private IPv4 addresses per ENI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI). For an `m5.4xlarge`, that would be 30. As mentioned earlier, the reason for this is to enable fast scale up, since attaching ENIs can be slow.

**Comment by minuki** [comment]
Sorry to comment on closed issue but could you please help me to understand above table especially for p3dn.24xl with WARM_IP_TARGET=5 and MINIMUM_IP_TARGET=2?

For 2nd and 3rd row, **Attached Secondary IP**s seems to be 8 and 15 respectively for me but don't understand how could be 5 and 12.


Instance type | WARM_ENI_TARGET | WARM_IP_TARGET | MINIMUM_IP_TARGET | Pods | Attached ENIs | Attached Secondary IPs | Unused IPs | IPs per ENI
-- | -- | -- | -- | -- | -- | -- | -- | --
p3dn.24xlarge | - | 5 | 2 | 0 | 1 | 5 | 5 | 5
p3dn.24xlarge | - | 5 | 2 | 3 | 1 | 5 | 2 | 5
p3dn.24xlarge | - | 5 | 2 | 10 | 1 | 12 | 2 | 12

**Comment by jayanthvn** [comment]
It looks like the assumption is there is just 1 attached ENI hence all IPs will be attached. I feel it can better represented so will update it.

**Comment by omidraha** [comment]
After we change the default values of them for example like this:

```bash
kubectl set env daemonset aws-node -n kube-system WARM_IP_TARGET=5
```
Is there any command to show the current values of `WARM_IP_TARGET`, `WARM_ENI_TARGET` and `MINIMUM_IP_TARGET`?
