### ISSUE TITLE
CNI Plugin unable to allocate ip Address to the container

### ISSUE THREAD

**Issue by sowhatim** [aws/amazon-vpc-cni-k8s#888]
This is the exact error - 

 Warning  FailedCreatePodSandBox  31m                   kubelet, ip-172-23-2-124.ap-southeast-1.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "94f4f58e8faa9ef25183a36f326a4c561be969a40a597fb52f149d36e53da053" network for pod "nginx-deployment-ff8f488fd-swnrf": NetworkPlugin cni failed to set up pod "nginx-deployment-ff8f488fd-swnrf_default" network: add cmd: failed to assign an IP address to container

I am using EKS, nodegroup with instance type t2.micro here.
No. of ip addresses (2*2) = 4 available. I can see that node has 4 ips bound to itself. 

I am running a nginx based deployment with pod having two containers. Interestingly I was successful in deployment with 3 replicas already, which means that atleast 1 node was already having two pods with 2 containers and thus 2 additional ips working out(apart from 2 that goes to aws-node and kube-proxy). 

But when just for sake of testing, I deleted the deployment and started with 1 replicas. And now it is stuck at this error. I can see that node has 3 pods assigned to it.

**Comment by sowhatim** [comment]
[describe-node.log](https://github.com/aws/amazon-vpc-cni-k8s/files/4398867/describe-node.log)
[describe-pod.log](https://github.com/aws/amazon-vpc-cni-k8s/files/4398868/describe-pod.log)

**Comment by mogren** [comment]
Hi @sowhatim, I since the CNI will only use the secondary IPs, on a `t3.micro` there will be two regular pods that can run. The `--max-pods` setting given in the [EKS AMI](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt#L248) is 4 because it takes the kube-proxy and aws-node pods into account. Both of these use host networking, so they don't require one of the secondary IPv4 addresses. CoreDNS will use these addresses though, and by default 2 CoreDNS pods will run in a new cluster. `t3.micro` is very small for a worker node, and you can consider running just 1 CoreDNS if you are just testing something small.

**Comment by sowhatim** [comment]
Hi @mogren . sure, got your point. 
I had the setup running one time but after changes to replicas, this problem started to happen. Though I have resolved now by recreating the cluster and it seems to be working fine.

**Comment by mogren** [comment]
@sowhatim great, thanks for update!
