### ISSUE TITLE
NetworkPlugin cni failed to set up pod "XXX" network: add cmd: failed to assign an IP address to container

### ISSUE THREAD

**Issue by tkbrex** [aws/amazon-vpc-cni-k8s#890]
CNI Plugin v1.5.5

I see: "Failed CNI request: add cmd: failed to assign an IP address to container"

I am using m5.2xlarge which has 4 interfaces. Each interface can assign 14 IP addresses. Hence, I only have total of 56 IP addresses. However, I am running 58 pod in the server. This is why couple new Pods cannot started because it cannot get IP address from CNI. I saw: "NetworkPlugin cni failed to set up pod "XXX" network: add cmd: failed to assign an IP address to container"

Questions:
1. CNI should kill the POD if it is running out of IP address ( which for some reason the pod is NOT killed )
2. Should I limit the pod per node to be 55 or should CNI handle it for me because only CNI know it is running out of IP address.

**Comment by tkbrex** [comment]
According to aws eks code,  m5.2xlarge can accept max 58 pod ( https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt#L119 ) but in the CNI log , it shows that it only have 56 IP addresses as:

2020-04-01T02:00:05.895Z [DEBUG]        IP pool stats: total = 56, used = 51, c.maxIPsPerENI = 14
2020-04-01T02:00:05.895Z [DEBUG]        IP pool is too low: available (5) < ENI target (1) * addrsPerENI (14)
2020-04-01T02:00:05.895Z [DEBUG]        Starting to increase IP pool size
2020-04-01T02:00:05.895Z [DEBUG]        Skipping ENI allocation as the instance's max ENI limit of 4 is already reached

Hence, is eks allow more pods (58) that CNI IP address available (56)

**Comment by mogren** [comment]
Hi @tkbrex! If you are using the standard EKS worker AMIs, the `--max-pods` flag will be set to `58` for `m5.2xlarge` instances because `kube-proxy` and the CNI (`aws-node` pod) also count against that limit. If you have 58 pods running, and one gets terminated, then another one get scheduled to the node, the CNI won't give the new pod the recently freed IP until a 30s cool-down has passed. This is because of the eventual consistency of Kubernetes where tearing down endpoints can take a while and we want to make sure that traffic doesn't get routed to the wrong pod. The kubelet should keep retrying the calls to the CNI to get an IP, so after a while the new pod should get an IP.

The reason that `kube-proxy` and `aws-node` does not need IPs is because they both use [host networking](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.5/config/v1.5/aws-k8s-cni.yaml#L80), that is they get a port mapped from the same IP as the instance they run on. This is all handled by the container runtime.

**Comment by mogren** [comment]
@tkbrex If you want I can take a look at your ipamd logs? We have a script to collect all logs:

https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script/linux

**Comment by tkbrex** [comment]
I send a direct mail for the log location.

For example, in log.tar.gz search for the following: "admin-api-v2-68dbb8b9b5-wl9h8" You can see that the pod is not created because CNI failed to assign IP address to the pod.

Thank you for following up.
Terence Kwan

**Comment by mogren** [comment]
@tkbrex Hi, sorry for the delayed update. Looking for errors in the logs I see the following:
```
14:42:15.919Z [DEBUG]    AssignIPv4Address: IP address pool stats: total: 56, assigned 52
14:42:15.919Z [ERROR]    DataStore has no available IP addresses
```
But a few seconds later
```
14:42:27.289Z [DEBUG]    AssignIPv4Address: IP address pool stats: total: 56, assigned 50
14:42:27.289Z [INFO] AssignPodIPv4Address: Assign IP 10.2.144.133 to pod
```
Meaning that the unused IPs are no longer in cool down. I you are running at 100% capacity, and have a lot of pod churn, some new pods might take a few extra seconds to come up. The kubelet should keep retrying to start the pod, and as soon as another IP is out of the cooling it should be assigned to the pod. The check for this is here: 

https://github.com/aws/amazon-vpc-cni-k8s/blob/8ffcd8a6168295df4ab2fd62d0cc3e3b5e4bae3d/pkg/ipamd/datastore/data_store.go#L315

**Comment by errogaht** [comment]
we have the same problem, but there is no good logs to fast understand the problem 
![image](https://user-images.githubusercontent.com/6324265/105346370-8a947680-5bf6-11eb-9b66-76f1d58b115f.png)

**Comment by akyhcs** [comment]
I am also facing same issue i updated my node pool and I got this error
