### ISSUE TITLE
Question about the number of network interfaces.

### ISSUE THREAD

**Issue by AVKarelin** [aws/amazon-vpc-cni-k8s#923]
Hi there
I have m5.large instance.
Image - amazon-k8s-cni:v1.5.7
The instance has only two interfaces, but according to the documentation there should be three.  Or am I missing something?

**Comment by mogren** [comment]
Hi @AVKarelin,

By default when a `m5.large` node starts, assuming you have the default configuration with `WARM_ENI_TARGET=1`, it should have one ENI attached with 9 secondary IPs available for pods. Once a (non host networked) pod gets scheduled to the node, it will get one of those IPs and 8 IPs will still be available. Next time the `aws-node` pod (The [IPAMD](https://en.wikipedia.org/wiki/IP_address_management) daemon of this CNI) checks how many available IPs it has, it will notice that 8 available is less than "one full ENI", which is 9. It will call EC2, create a new ENI, attach it to the node, then attach 9 new secondary IPs to that ENI. Now there are 2 ENIs attached 1 IP used by a pod and 17 available IPs. Once 9 more pods have been scheduled to the node, 'aws-node' will attach the third ENI. 

The `--max-pods` flag of an `m5.large` will be 29, 3 ENIs with 9 secondary IPs, plus 2 because `kube-proxy` and `aws-node` is using host networking, meaning that they count as pods, but don't use up secondary IPs because they are sharing the node IP.

There are settings that can change this, for example increasing the `WARM_ENI_TARGET` higher, or using `WARM_IP_TARGET` (only for running few pods with low pod churn). Or if `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG` is set to `true`, meaning you want to get the node IP and pod IP from different CIDRs and to have different Security Groups, the first ENI will only be used for the node, and the secondary IPs on the other two ENIs for pods. It is also possible to run out of IPs in a small subnet, making it impossible to create more ENIs.

**Comment by mogren** [comment]
@AVKarelin Please reopen if your question was not answered.
